### ISSUE TITLE
Lost google pixel launcher after installing

### ISSUE THREAD

**Issue by siddharthalodha** [Kingsman44/Pixelify#1]
Hey,
Thanks for the mod. I tried installing it on my pixel 2 stock rom. I used the latest release version (6th May one) 

It removed the pixel launcher and there was no way to get it back. I can see the file(NexusLauncher) is still there in the system folder.

Some other observations :

1. Adaptive charging gets enabled but doesn't work on my phone. Were you able to get it working ? 
2. Screen attention works. ( Can you tell me how do you enable it ?) I am using another mod right now which works better for my phone. I can integrate those changes in that mod. 
3. NGA works
4. Didnt try other features like Fit, Duo features. 

Also, is there a way to get extreme battery saver also work ?

**Comment by Kingsman44** [comment]
Sorry for pixel launcher,
Can you tell Did you select Yes or No in Pixel Launcher?
(temp fix:- go to /data/adb/modules/Pixelify/system/product/priv-app
delete NexusLauncherRelease folder from there)

it should be fixed on v1.3

1) Adaptive Charging was introduced in Dec 2020 Pixel Drops requires codes from Google Android Source.
as i remember Pixel 2 latest version was Nov 2020, so it won't gonna work before Dec 2020 Patch
[ Try this on own Risk
You can try updating GoogleSystemUI and framework-res.apk from pixel 3 as all same for pixel stock phones might work adaptive charging ]

2) Screen Attention were Enabled from DevicePersonalisationServices apk.
you can force enable them by overlays of android

<string name="config_defaultAttentionService" translatable="false">com.google.android.as/com.google.android.apps.miphone.aiai.attention.service.AiAiAttentionService</string>

Extreme battery is also depends on Google SystemUI after Dec patch 20.

Thanks for trying my module

**Comment by siddharthalodha** [comment]
Thanks for the help. Yeah i had to uninstall magisk, then i took the latest code and flashed it. 
I had earlier replaced the pixel launcher for double tap to sleep and that had caused the issue. Thanks for fixing that.

Yeah, I was able to enable all features now except Adaptive Charging and Extreme battery saver. Although, Pixel 2 xl got updates till December but i believe Nov,Dec were only security patches so it doesn't have the necessary code to run.

Also, just another pointer, I seem to have lost the Enhanced voice typing in my gboard. I tried all things, i think it looks like a server side thing from Google. 

Also, I had discovered Hold for me feature and was able to enable in my pixel phone. But it only works if i dial a US toll free number which i don't do generally. Would you know of any way to activate hold for me for all numbers ?

**Comment by siddharthalodha** [comment]
Also, i didn't understood how you enabled Screen Attention. Can you tell me the steps in more detail ?

**Comment by Kingsman44** [comment]
> Thanks for the help. Yeah i had to uninstall magisk, then i took the latest code and flashed it.
> I had earlier replaced the pixel launcher for double tap to sleep and that had caused the issue. Thanks for fixing that.
> 
> Yeah, I was able to enable all features now except Adaptive Charging and Extreme battery saver. Although, Pixel 2 xl got updates till December but i believe Nov,Dec were only security patches so it doesn't have the necessary code to run.
> 
> Also, just another pointer, I seem to have lost the Enhanced voice typing in my gboard. I tried all things, i think it looks like a server side thing from Google.
> 
> Also, I had discovered Hold for me feature and was able to enable in my pixel phone. But it only works if i dial a US toll free number which i don't do generally. Would you know of any way to activate hold for me for all numbers ?

Try Force stopping Gboard and check this fixes for me,
If not fixed then try clear data of Gboard, open it once and reboot.

Can you tell where you live? Is Hold for me and latest ed call screening work without US.

For adaptive charging can you send logs,
So that I can look into it and find what's crashing in it.

**Comment by Kingsman44** [comment]
> Also, i didn't understood how you enabled Screen Attention. Can you tell me the steps in more detail ?

Create system overlay. With this string
< string name="config_defaultAttentionService" translatable="false">com.google.android.as/com.google.android.apps.miphone.aiai.attention.service.AiAiAttentionService>

Also can tell smart compose working for you or not?
go to Gboard Setting> Text correction> Smart Compose should be there.

**Comment by siddharthalodha** [comment]
I had already received Smart Compose before installing the mod. So, that was already working.

Also, How do i create system overlay ? Do i need to modify the apk ? Sorry, I am not aware of this.

For getting call screening, I used Market Unlocker and changed my market to Verizon US

**Comment by Kingsman44** [comment]
> I had already received Smart Compose before installing the mod. So, that was already working.
> 
> Also, How do i create system overlay ? Do i need to modify the apk ? Sorry, I am not aware of this.
> 
> For getting call screening, I used Market Unlocker and changed my market to Verizon US

Can send apk of that?
