### ISSUE TITLE
pixel  launcher disappeared

### ISSUE THREAD

**Issue by hyjklmn** [Kingsman44/Pixelify#10]
PE rom. When I installed the pixel launcher, if I uninstalled the module, the pixel launcher was uninstalled after restarting

**Comment by webstudyer** [comment]
And other installed effects still exist, such as gboard redesign And adaptive sound

**Comment by Kingsman44** [comment]
Which Rom? Which Device? and Android Version?

**Comment by webstudyer** [comment]
> 哪个设备？和安卓版？

one plus 5t  a11

**Comment by Kingsman44** [comment]
I shouldn't disppeared, also it doesn't happend here. Anyway i will try my best to fix this problem.
