### ISSUE TITLE
Google Dialer went back to normal after changing fingerprint to pixel 5

### ISSUE THREAD

**Issue by ShadowHunterKK** [Kingsman44/Pixelify#103]
Using Xiaomi Mi 10T Lite( gauguin)
LineageOS 19.1( A12.1).
So I tried to use the call screening and the caller wouldn't hear the Assistant. After a bit of searching I saw someone saying to have the Pixel 5 Fingerprint and I had Pixel 4a.
I changed the fingerprint to Pixel 5. About 30 mins ago I tried again and the caller couldnt hear it. I check now to see something and zi see that it disappeared. Why did this happen?
![Screenshot_20220616-000429_Termux.png](https://user-images.githubusercontent.com/60347401/173930470-e9f9615c-d27e-4234-aa17-293e17f6d895.png)
![Screenshot_20220616-000434_Phone.png](https://user-images.githubusercontent.com/60347401/173930484-a58a41a6-97b8-46bb-8c8a-7b885133cc56.png)

**Comment by ShadowHunterKK** [comment]
[Logs in case it helps](https://www.dropbox.com/s/mqx8u1dugc7n42r/Get%20Started%20with%20Dropbox%20Paper.url?dl=0)

**Comment by Kingsman44** [comment]
Reinstall pixelify
