### ISSUE TITLE
Fast battery drawing

### ISSUE THREAD

**Issue by Red-Baran** [Kingsman44/Pixelify#104]
I'm not sure why but as soon as I flashed this I am no longer able to fast charge. In fact I cant see 0.5w/500mA. I have tried everything. Is this even possible?

**Comment by eclipsek20** [comment]
Could you be a little more specific?

**Comment by Red-Baran** [comment]
Oddly as soon I set up Pixelify my tablet wouldn't fast charge or even
standard charge. Before I was charging around +4,800mA after install +300mA
(or less)

**Comment by Kingsman44** [comment]
Will check.

**Comment by Kingsman44** [comment]
battery is improved in v2.1, if you still facing it plz reopen it
