### ISSUE TITLE
Android System Intelligence crashing (Root cause: Play store)

### ISSUE THREAD

**Issue by UltraHQ** [Kingsman44/Pixelify#108]
Android System Intelligence wants to update to the Pixel 4 version via the Google Play Store.
When this happens, it will spam-crash. The only fix is, to uninstall updates from it (resetting to factory version)

Disabling auto-updates will not fix the issue, as google decides to update the app anyway after some days

My device:
Samsung Galaxy A72
OneUI 4 (Android 12)

Installed (working) Android System Intelligence version: `S.7.sysimg.oem.406886639`
Used module version: `v2.1-beta-1`

**Comment by Kingsman44** [comment]
can you send me crash logs of Android system intelligence?

**Comment by L8Black** [comment]
Is there a fix?
