### ISSUE TITLE
Overlay causing issues with some OEMs

### ISSUE THREAD

**Issue by duramato** [Kingsman44/Pixelify#109]
- Oneplus 8
- Android 12
- Version 2.1-beta-2

When installing the overlay a round hole near the supposed camera location appears and the clock disappears from the statusbar. The power button seems to be remapped from opening the power menu, to opening the Google Assistant. To open the power menu I need to do Power+Vol Up.

I've experienced this with other magisk modules that install overlays. This is because on Oneplus, on some samsungs, magisk doesn't seem to work with `/system/product/overlay` and needs to use `/system/vendor/overlay`.

More info on an issue i've created on another magisk module: https://github.com/KieronQuinn/AmbientMusicMod/issues/51#issuecomment-1162126369

Quickswitch which also mounts overlays with magisk doesn't have this issue for me, as from what I found from QuickSwitch's source that different device vendors handle overlays differently. So might be needed to implement some check like this: https://github.com/skittles9823/QuickSwitch/blob/master/quickswitch#L134-L193 

![image](https://user-images.githubusercontent.com/10121067/182023918-c9d3ff70-ed4b-440e-b876-f25d9ab49613.png)

I've tried fixing it, by changing costumize.sh to write to `vendor` as well as changing the system.tar.gz paths from `product` to `vendor` and it seems to work, but I'm not experienced enough to know if I've did it all correctly. 
My changed `system.tar.xz` filetree:
```
├───etc
│   ├───firmware
│   ├───sysconfig
│   └───textclassifier
├───fonts
├───product
│   ├───framework
│   ├───media
│   │   └───audio
│   │       ├───alarms
│   │       ├───notifications
│   │       ├───ringtones
│   │       └───ui
│   └───priv-app
├───system_ext
│   └───lib64
└───vendor
    ├───app
    │   └───MicropaperPrebuilt
    ├───etc
    │   ├───default-permissions
    │   ├───permissions
    │   └───sysconfig
    └───overlay
        └───OneHandedModeGesturalOverlay
```

If you need any logcat to debug this further let me know.

**Comment by Kingsman44** [comment]
This is fixed in v2.1
