### ISSUE TITLE
Bootloop on Oneplus 9

### ISSUE THREAD

**Issue by gerardovasquez307** [Kingsman44/Pixelify#11]
Oneplus 9 on latest OOS 11 updated from 1.4 to 1.5 caused bootloop. Currently booting into twrp to manually uninstall module. Reverting back to 1.4

**Comment by gerardovasquez307** [comment]
also chose yes to all options except spoof pixel 5, pixel launcher, pixel boot animation, and pixel live wallpapers

**Comment by gerardovasquez307** [comment]
I was able to recover with twrp and remove 1.5 module. I tried reinstalling 1.5 again and had a bootloop again. I removed 1.5 via twrp and reinstalled 1.4 and confirmed to be working fine. I will stay on 1.4 for now

**Comment by Kingsman44** [comment]
Sorry about that. I may think it's because of Extreme Battery Saver. I will make it optional to install also try to fix bootloop in some devices

**Comment by Kingsman44** [comment]
It should be fine Now in Pixelify V1.6, if any problem please let me know
