### ISSUE TITLE
Stuck on android is starting on Samsung M01 Core 

### ISSUE THREAD

**Issue by SwissChocolateBrownie** [Kingsman44/Pixelify#114]
downloaded the zip and installed it with all the features and after a reboot the phones was stuck on android is starting had to go to the settings to go into magisk and disable it and reboot to fix it

**Comment by Kingsman44** [comment]
I need logs to check the problem.

**Comment by SwissChocolateBrownie** [comment]
[logs.txt](https://github.com/Kingsman44/Pixelify/files/9294004/logs.txt)
you mean these logs right? there you go!

**Comment by diogosilva30** [comment]
Happening the same to me on Samsung Tab A with all features enabled

**Comment by Kingsman44** [comment]
Don't enable Next generation assistance it is causing bootloop

**Comment by diogosilva30** [comment]
[logs.txt](https://github.com/Kingsman44/Pixelify/files/9484922/logs.txt)
@Kingsman44 I factory reset the tablet, tried again without NGA and the same thing happened.
Stuck in "Starting Android"

**Comment by Kingsman44** [comment]
If you got starting android then don't enable Pixel launcher

**Comment by diogosilva30** [comment]
@Kingsman44 I'll try that. Will give feedback soon

**Comment by SwissChocolateBrownie** [comment]
@Kingsman44 ill check it out aswell

**Comment by diogosilva30** [comment]
This time I didn't enable almost any extra feature, except Extreme Battery Saver and Google Settings Service, and can confirm that the device is no longer stuck on "Starting Android"

**Comment by SwissChocolateBrownie** [comment]
i mainly wanted the pixel launcher but it seems to be incompatible with my device for some reason too bad lol still a good module for the devices it actually works with ill be  closing this now thnx to @Kingsman44 and @diogosilva30 for helping me out here 
Godspeed gentlemen!
