### ISSUE TITLE
Audio Problem; System UI Lags

### ISSUE THREAD

**Issue by Domniak** [Kingsman44/Pixelify#116]
Hey, so ive recently installed the Pixelify module and I wanted to try out Now Playing, now I have playback issues resulting the system ui to lag out. So I tried to install pixelify again without Now Playing, but the Issue persists. Ive been told to make a log, but the log data is incredibly long.

Device: Xiaomi 11T Pro
GSI Rom: SparkOS 12.6
Android 12L

**Comment by Domniak** [comment]
Guys, if any of you installed the stable version 2.02, try to install the beta version and disable now playing, this solved my issue

**Comment by ziddey** [comment]
Different device, but same issue.

moto edge 2021 xt2141-2 (berlna).

With 2.02, audio was more or less fine as long as now playing is disabled.

But with 2.1, audio constantly crashes regardless of now playing. `audio_playform_info.xml` is changed with this module?

![Screenshot_20220920-210512](https://user-images.githubusercontent.com/3846501/191404419-4f3057fc-08c8-4885-8a07-9ba8f7432ef2.png)

![Screenshot_20220920-211942](https://user-images.githubusercontent.com/3846501/191404426-6ee2d386-dbc0-4d9f-b910-121b7ea13600.png)

**Comment by drkui** [comment]
I'm getting the same as Ziddey on 2.1. I had to revert back to 2.02 to get my audio to work properly. Anyone know if this has been fixed in the latest 2.2 beta?

**Comment by memehammad** [comment]
Same issue here on 2.2 on a Redmi Note 10 Pro.
