### ISSUE TITLE
Solved: How to install on Windows 11

### ISSUE THREAD

**Issue by liero0** [Kingsman44/Pixelify#121]
Thanks for this pixel hack, really appreciated. [I already tried this  on Android X86 9.0 on VirtualBox and it works fine.
](https://i.imgur.com/iNe1EBM.png)

Could someone help with installing this on Windows Subsystem for Android?

I installed the Android for Windows 11 using the instructions on this site:
https://www.androidsage.com/2022/06/28/download-wsa-android-12-1-with-magisk-root-google-play-store/

Then I installed Magisk using these instructions:
https://www.getdroidtips.com/root-windows-subsystem-for-android-via-magisk/

So, now I have a fully working WSA with Google services and Magisk works, but how to flash pixelify? The 'normal' version stops to an error about volume keys, so I think I need to download Pixelify-v2.1-no-VK.zip. 

How about installation? I already copied the config.prop to internal folder, but then what? This is clearly not enough. Then I flashed the zip with magisk, but I still don't have unlimited storage in google photos (I did erase photos app's data after flashing).

EDIT:
I got this. I forgot to enable 'zygisk'. Now it works.

**Comment by morhadi** [comment]
I have zygisk enabled but everytime i flash the module and reboot magisk it shows nothing in installed modules. do you have any idea?

**Comment by morhadi** [comment]
After reading logs I can see, It is showing 2 errors 

1. - Installing Google Photos from backups

Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 48627807 is older than current 48849424]
- Please Disable Google Photos Auto Update on Playstore
chmod: /data/data/com.google.android.dialer/files/phenotype: No such file or directory
  Google is installed.

Comment : This shows even though auto update is turned off on play store

**Comment by bjungbogati** [comment]
Try using release [WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0.7z)

from https://github.com/MustardChef/WSABuilds/releases

![image](https://github.com/Kingsman44/Pixelify/assets/8600091/256e01a8-99d0-4688-87f4-fc2e7bbd0a6f)

**Comment by morhadi** [comment]
> everytime i flash the module and reboot magisk it shows nothing in installed modules.

Update :
If I dont reboot it shows pixelify in installed modules and works fine but if i close wsa once or reboot magisk it doesnt show in installed modules.
