### ISSUE TITLE
Substratum theme conflict

### ISSUE THREAD

**Issue by gerardovasquez307** [Kingsman44/Pixelify#14]
I have a substratum theme to do a black AMOLED background on all of the Google applications. I had another device that had the latest Gmail and the latest Google Dialer app and substratum theme worked fine. After updating to 1.6 it seems that whatever theming is happening in the background when installing this module is taking over the associated backgrounds to all the apps and substratum cannot seem to overwrite them. is there any way that the theming and accents applied through this module is optional? I have tried recompiling/rebuilding all of the themes through substratum and the issue persists. 1.6 is the only module that this issue has occurred.

**Comment by Kingsman44** [comment]
Problem occurred in Google dialer app only or all Google apps?

**Comment by gerardovasquez307** [comment]
All Google apps. Once I installed this module, all amoled backgrounds associated with the apps were overwritten by your module. I see that you mentioned accent fixes in your latest release I'm sure it's related to that.

**Comment by Kingsman44** [comment]
Which Android version? Accent Fix is nothing but due to pixel before android 12 uses Blue Accent color as default on overlay it was conflicting with monet as monet is dynamic and overlay made it static color.

**Comment by gerardovasquez307** [comment]
Oxygen os 11 stock rom, on pixelify 1.6 using substratum liv dark theme. I did not select yes for spoofing to pixel for the options in installation
