### ISSUE TITLE
Pixelify causes massive lags

### ISSUE THREAD

**Issue by 10Maximus10** [Kingsman44/Pixelify#150]
Hello after installing Pixelify my phone is so slow that I couldn't even turn it off. This module looks amazing but it's impossible for me to use it. My phone is Motorola moto g7 power on stock a10.

**Comment by Fede2782** [comment]
I'm using it on Moto G7 with lineages and it works better that the stock os

**Comment by 10Maximus10** [comment]
> I'm using it on Moto G7 with lineages and it works better that the stock os

But I don't want to use lineageos.

**Comment by Fede2782** [comment]
I'll test it on my other Moto G7 with stock ROM (10) in a few days

**Comment by 10Maximus10** [comment]
So have you tested it yet?

**Comment by 10Maximus10** [comment]
> I sorry I completely forgot, however I tested it on a clean install, so without data and used everything except for pixel launcher and works fine.

On android 10 or 9?

**Comment by Fede2782** [comment]
10 with latest patch (Feb 2021)

**Comment by Fede2782** [comment]
But everything crash when I open wallpaper and styles

**Comment by 10Maximus10** [comment]
Then I guess something is wrong with my setup. Because it's a problem on my side I am closing this issue as I don't have time to try it on a clean install.
