### ISSUE TITLE
google photos (smart eraser) unable to install due to android 13

### ISSUE THREAD

**Issue by nityanantan23** [Kingsman44/Pixelify#158]
When installing the google photos (smart eraser) apk in android 13, it says newer version is installed and cant install the smart eraser version.

**Comment by Thisisauser6443** [comment]
All you need to do is uninstall the updates from the original Google Photos app, via `App Info` > Hamburger Menu (3 dots on the top right) > `Uninstall updates` (At least, that's how you'd do it, on a stock Pixel ROM, but it varies to an undeterminable degree across other OEMs)
