### ISSUE TITLE
NGA Voice typing not working

### ISSUE THREAD

**Issue by Reiux** [Kingsman44/Pixelify#159]
I Successfully Installed Pixelify on my phone and it works flawlessly except NGA Voice typing is not working when I check my Gboard settings to enable it it says

 "To use assistant voice typing, Update your Android System Intelligence app on Google play." 

then I updated it through apkmirror from R.26 pixel 5 to R.30 pixel 5.
But it's still not working is there any way to fix it?

![Screenshot_2022-12-26-02-41-34-28_729f5fd1bce94da8617f218da402b3c8.jpg](https://user-images.githubusercontent.com/90865965/209477792-12b0f417-8b45-4862-9b20-e8a9b5722f6d.jpg)

**Comment by Kingsman44** [comment]
Android 11 doesn't support NGA Typing, due to missing codes in ASI. You need to update to Android 12 or above.
