### ISSUE TITLE
Call Screening stuck on "Activating Call Screen (Requires Wi-Fi)"

### ISSUE THREAD

**Issue by vaishnavvprabhu** [Kingsman44/Pixelify#16]
Hello,
Firstly thank you for this amazing module. It has helped us a lot to live our "pixel dreams". I do seem to have a problem here. When I installed the latest version of pixelify, the phone app seems to be stuck on activating call screening (as shown in screenshot). I tried setting my wifi as an unmetered connection, force stopping phone app, clearing data and even reinstalling the module but nothing seems to fix it. 

![Screenshot_20211005-160646943](https://user-images.githubusercontent.com/67993582/136007668-861e2e4b-bd16-4b6e-90a6-dafc924ff813.jpg)

**Comment by Kingsman44** [comment]
Set default system language to en-US and force stop
