### ISSUE TITLE
Screen Calling and Google Recorder transcription not working

### ISSUE THREAD

**Issue by Reiux** [Kingsman44/Pixelify#160]
Hello,

I just want to know why the transcription is not working on Screen calling and Google recorder.

I did install the English (US) offline language pack and it's on version 8032 but the Troubleshooting steps said that version 7xxx is for tensor chips while 5xxx is the one that's working. So how can I install the v5xxx Language pack?

![Screenshot_2022-12-27-03-27-38-87_a2f4758f9c0a9fa4d0ad0d47e2b8dd16.jpg](https://user-images.githubusercontent.com/90865965/209575339-1e239c33-c2a2-43d0-bb87-5cfb20f07e94.jpg)
![Screenshot_2022-12-27-03-40-20-68_680d03679600f7af0b4c700c6b270fe7.jpg](https://user-images.githubusercontent.com/90865965/209576015-91e09657-ddaf-47bc-b29c-078a752fe9f2.jpg)

**Comment by Kingsman44** [comment]
click on uninstall.

**Comment by Reiux** [comment]
> click on uninstall.

Okay done. what's next?

Cause I can't be able to use the transcription without a Language pack it's going to ask me to download it again.

**Comment by K-plus69** [comment]
Where did you uninstall the languages?

**Comment by Reiux** [comment]
> Where did you uninstall the languages?

I uninstalled it on Google app> Your profile picture on the top right corner> Settings> Voice> Offline speech recognition

Then I uninstall the English (US) language pack from there.

**Comment by Reiux** [comment]
Closing this issue because of the new beta 4 fix this issue.
