### ISSUE TITLE
Original Unlimited upload no longer available

### ISSUE THREAD

**Issue by Jerithub** [Kingsman44/Pixelify#17]
It appears that backup photos are now counting against the google storage. The images that were uploaded previously using v1.6 also started counting against it.

I have a P4 and I should get unlimited storage for the Storage Saver option, but it doesn't. It simple recognize my device as a non-pixel device.

Can you make the Pixel spoof on Google Photos to be optional instead?

**Comment by Kingsman44** [comment]
Okay, I will to fix it if it can't able to fix it then I will make optional
