### ISSUE TITLE
Live caption doesn't have other languages 

### ISSUE THREAD

**Issue by srt54558** [Kingsman44/Pixelify#184]
Device name: Huawei p20 lite 
Rom name: LeaOS 13
Android version: 13, February patch
Pixelify version: 2.2

Bug Description: After installing the 2.2 version, only english live caption is available.

![Screenshot_20230330-205958.png](https://user-images.githubusercontent.com/90862487/228937447-bbd8ab9f-76b3-4fa6-bdd8-997107f17a5c.png)

Sprachen=languages (German)
"Only available on English. More languages are coming soon"

**Comment by ImLoadingUuU** [comment]
This isn't a bug
