### ISSUE TITLE
Bootanimation Optimization

### ISSUE THREAD

**Issue by Prasoon-kushwaha** [Kingsman44/Pixelify#21]
Pixel bootanimation is optimised for 1080p display only, it would be great to have option for 720p , 1080p and 1440p display or auto-dectection and flashing of appropriate bootanimation from ☁️ would be great.

**Comment by Kingsman44** [comment]
This can be done, maybe implemented on future.

**Comment by Kingsman44** [comment]
Its added in Pixelify v2
