### ISSUE TITLE
Call Screening Not Heard

### ISSUE THREAD

**Issue by zxkriya** [Kingsman44/Pixelify#22]
Poco X3 NFC, Android 11 on ArrowOS.
Call Screening can't be heard on the other end.

**Comment by Kingsman44** [comment]
Well, it works for me after audio hal v6 and mixer paths for music up link.

looking Arrow 11 surya trees, looks it's already present.
still looking for reason for this. but this is device related. not module's fault.

it will tell you if i find out anything.

**Comment by zxkriya** [comment]
Maybe it's something to do with VIPER4ANDROID and AUDMOD library?

**Comment by zxkriya** [comment]
modification*

**Comment by Kingsman44** [comment]
i dont think it is, but better to check it.

**Comment by zxkriya** [comment]
didn't fix the issue. it sounds like it's sorting of lagging? I'm not sure how to describe it. Hoping for a fix soon.

**Comment by Kingsman44** [comment]
As this is duplicate issue, I am closing this

for future reference comment on this https://github.com/Kingsman44/Pixelify/issues/12
