### ISSUE TITLE
Bootloop Samsung Galaxy A51 (4G)

### ISSUE THREAD

**Issue by ItsLynix** [Kingsman44/Pixelify#23]
Galaxy A51 on Android 11 + OneUI 3.1, installing Pixelify causes a bootloop where the samsung logo is displayed, then it fades out, reboots, and reappears.

If force shutdown while bootlooping, device restarts and boots up again normally but all magisk modules have been unloaded and are not detected again until next reboot.

Options chosen:
Spoof = Yes
Next-Gen Assistant = Yes
Live Wallpapers = Yes
Boot Animation = No
Launcher = Yes
Extreme Battery Saver = No

Magisk Install Log
[magisk_install_log_2021-11-02T15_43_17Z.log](https://github.com/Kingsman44/Pixelify/files/7463640/magisk_install_log_2021-11-02T15_43_17Z.log)
:

And if you need it, here's a full system log
[logcat.log](https://raw.githubusercontent.com/ItsLynix/ItsLynix.github.io/main/cdn/Pixelify-Issue-23/logcat.log)
:

**Comment by ItsLynix** [comment]
Here's a full system boot log if you need it xD

(File too large for github)
`https://drive.google.com/file/d/1Da6S7xp5zzSwRF-jxzNgUpqittWiTg5A/view?usp=sharing`

**Comment by Kingsman44** [comment]
thanks for reporting, it will be fixed on next update

**Comment by Kingsman44** [comment]
can try on this version, it working or not ?
https://drive.google.com/file/d/1CqOzG5UjmapY5vBTvQWaqaZ-kXzXZAl6/view?usp=sharing

**Comment by ItsLynix** [comment]
Appears to still be bootlooping

**Comment by Kingsman44** [comment]
can send this file? /sdcard/Pixelify/logs.txt

**Comment by ItsLynix** [comment]
https://drive.google.com/file/d/1HpZ-0b5uwPrivWvAmPOqeGH1nCmxYjKv/view?usp=drivesdk

**Comment by Kingsman44** [comment]
> https://drive.google.com/file/d/1HpZ-0b5uwPrivWvAmPOqeGH1nCmxYjKv/view?usp=drivesdk

Thanks, everything fine here, can send boot logs?

**Comment by ItsLynix** [comment]
What's your timezone? I'll probably have to get a logcat via adb to do it and I'm not at a PC right now

**Comment by Kingsman44** [comment]
Can also try installing without Pixel Live Wallpapers?

**Comment by Kingsman44** [comment]
> What's your timezone? I'll probably have to get a logcat via adb to do it and I'm not at a PC right now

IST, no problem when u have access to pc give me that time. I will wait

**Comment by ItsLynix** [comment]
> Can also try installing without Pixel Live Wallpapers?

Yeah I'll try without that

**Comment by ItsLynix** [comment]
> > What's your timezone? I'll probably have to get a logcat via adb to do it and I'm not at a PC right now
> 
> IST, no problem when u have access to pc give me that time. I will wait

Alright thank you

**Comment by ItsLynix** [comment]
IST, that's indian time right? I must say your English is truly great, good job.

I'll be trying installing it without animated wallpapers in just a little bit

**Comment by ItsLynix** [comment]
Alright, just tried without the live wallpapers and it still went on to bootloop, I'll catch up more on this with a logcat as soon as I get home

**Comment by ItsLynix** [comment]
Hey, apologies for the delay, I'll be getting the boot log for you today

**Comment by Kingsman44** [comment]
> Hey, apologies for the delay, I'll be getting the boot log for you today

No Problem, take you time, Thanks in advance for the logs

**Comment by ItsLynix** [comment]
Alright, and here's the boot log.
[logcat2.log](https://raw.githubusercontent.com/ItsLynix/ItsLynix.github.io/main/cdn/Pixelify-Issue-23/logcat2.log)

**Comment by Kingsman44** [comment]
> Alright, and here's the boot log. [logcat2.log](https://raw.githubusercontent.com/ItsLynix/ItsLynix.github.io/main/cdn/Pixelify-Issue-23/logcat2.log)

Thank you, I will check it tomorrow

**Comment by ItsLynix** [comment]
Alright, Thanks

**Comment by Kingsman44** [comment]
Bootloop is should be now fixed,
Sorry feeling very sleepy (2 Am here)
I will send you test build tomorrow.

**Comment by Kingsman44** [comment]
[Pixelify-v1.81.zip](https://github.com/Kingsman44/Pixelify/files/7594344/Pixelify-v1.81.zip)
there you go, sorry for the delays

**Comment by ItsLynix** [comment]
Alright let me try it out

**Comment by ItsLynix** [comment]
Alright, now the phone reboots to SafeMode SystemUI, aka the oneui safemode

**Comment by Kingsman44** [comment]
What's that?

**Comment by ItsLynix** [comment]
https://media.discordapp.net/attachments/835062581378154536/913012217966895104/Screenshot_20211124-112410_One_UI_Home.jpg

**Comment by ItsLynix** [comment]
Accident

**Comment by Kingsman44** [comment]
Can't we boot to normal system UI even after reboot?

**Comment by ItsLynix** [comment]
Nope, it bootloops once then goes to safemode

**Comment by Kingsman44** [comment]
Can provide logs? Thanks in advance

**Comment by ItsLynix** [comment]
> Can provide logs? Thanks in advance

Give me a bit

**Comment by Kingsman44** [comment]
Sure, take your time. I will wait.

**Comment by ItsLynix** [comment]
So, here is the log of when the device fails to boot once after install
[installboot.log](https://raw.githubusercontent.com/ItsLynix/ItsLynix.github.io/main/cdn/Pixelify-Issue-23/installboot.log)
:

And here is the log of when the device boots to systemui safemode after the first failed boot
[safemodeboot.log](https://raw.githubusercontent.com/ItsLynix/ItsLynix.github.io/main/cdn/Pixelify-Issue-23/safemodeboot.log)
:

**Comment by Moekingbad** [comment]
Hello @ItsLynix @ChrisvanChip  was this solved?

**Comment by ChrisvanChip** [comment]
> Hello ItsLynix @ChrisvanChip was this solved?
Sorry, I do not maintain the OS so I am unable to provide an answer on that 🙈

**Comment by ItsLynix** [comment]
This issue was never solved as far as I am aware, after author stopped responding I had enough and started experimenting with GSIs instead

**Comment by Kingsman44** [comment]
> Hello @ItsLynix @ChrisvanChip was this solved?

Sorry, it's not fixed on Samsung Galaxy A51 (4G). I don't have enough time for now. As i didn't find simple solution. I need to lookout every single overlay code.  I probably look out in starting of January.

But yeah bootloop on Samsung S10 lite was solved
https://github.com/Kingsman44/Pixelify/issues/31

**Comment by Kingsman44** [comment]
Also sorry to @ItsLynix, you provided logs and everything.
Sorry I got busy with my colleges admission. I definitely try to fix in starting of january.

**Comment by Kingsman44** [comment]
Does still v2 bootloop?
i added some fix for it.

**Comment by ItsLynix** [comment]
Hi @Kingsman44 apologies for not testing anything,  I just tested and it does not bootloop

**Comment by ItsLynix** [comment]
Though I am curious, is it supposed to switch the default launcher when pixel launcher is enabled? Because that it has not

**Comment by Kingsman44** [comment]
Try latest beta for pixel launcher
https://t.me/pixelifysupport/16388
