### ISSUE TITLE
Some features are not available without pixel spoof

### ISSUE THREAD

**Issue by usrDottik** [Kingsman44/Pixelify#24]
In the readme.md file there is Adaptive Sound, but the feature needs to have pixel spoof enabled, and if you installed Android System Intelligence before, you have to uninstall it, then install it again, and reboot, then the option will show up on Sound settings, I make this issue to say that maybe you should replace Android System Intelligence if you spoof the device, so the features that are supposed to work work correctly.

**Comment by Kingsman44** [comment]
It does actually replace it with system. But actually updated from playstore overide it.

**Comment by usrDottik** [comment]
Thanks for answering
