### ISSUE TITLE
Problems connecting to some google servers

### ISSUE THREAD

**Issue by N367B** [Kingsman44/Pixelify#25]
When I activate this module, I can't connect to some of Google's servers (can't download apps on the play store, can't connect to RCS in google messages, etc.). I don't know what's causing this.

Most of the notifications are also blocked sometime.

**Comment by Kingsman44** [comment]
I don't think it module related. I used this all the time no problem here

**Comment by N367B** [comment]
I used it a lot, but when I switched to android 12 I'm having this issue, but only when the module is activated, so is most likely caused by it.
Also, since I'm here, the select option in recent tab doesn't work well with text

**Comment by niikoo** [comment]
I also have some similar issues. Apps in the play store are stuck in "pending" and the Google dialer complains about my device being an "unsupported device".

**Comment by N367B** [comment]
> I also have some similar issues. Apps in the play store are stuck in "pending" and the Google dialer complains about my device being an "unsupported device". A11

Yeah that's what happening to me. And some more problems too

**Comment by Quantizr** [comment]
I have the same problem with this module, it fixes itself when removed. Android 12, Essential PH-1 on GSI Lineage ROM

**Comment by N367B** [comment]
Here are some logs :
- One of the installation process.
- The other when it is installed (can't install anything from play store(always on “pending”, and some more connectivity issues
Hope it can help, it would be perfect if those issues wouldn't spoil everything[](ur
[logcat_11-16-2021_21-03-30.txt](https://github.com/Kingsman44/Pixelify/files/7549523/logcat_11-16-2021_21-03-30.txt)
[logcat_11-16-2021_21-07-33.txt](https://github.com/Kingsman44/Pixelify/files/7549525/logcat_11-16-2021_21-07-33.txt)
l)

**Comment by N367B** [comment]
After some time and multiple installions it seems to be working fine for now

**Comment by Kingsman44** [comment]
Please Check, Does this problem still exist on v1.8
it works fine here.

**Comment by N367B** [comment]
> Please Check, Does this problem still exist on v1.8? it works fine here.

It doesn't seem to be working for now. I will wait for a bit. Now the select option in the recent tab is working way better than before

**Comment by N367B** [comment]
It doesn't seem to be working even after a reboot and few hours of waiting. What should I do to help you solve that ?

**Comment by Kingsman44** [comment]
> 

can try without spoof?

**Comment by N367B** [comment]
> > 
> 
> can try without spoof?

It seems to be working, except I get "Android System Intelligence keeps stopping" several times. And the select option doesn't seem to be working
![Screenshot_20211120-111440_Messages~2](https://user-images.githubusercontent.com/42220691/142722742-5dd1addf-8f85-435b-8902-0ce5a59239fd.png)

**Comment by Kingsman44** [comment]
> > > 
> > 
> > 
> > can try without spoof?
> 
> It seems to be working, except I get "Android System Intelligence keeps stopping" several times. And the select option doesn't seem to be working ![Screenshot_20211120-111440_Messages~2](https://user-images.githubusercontent.com/42220691/142722742-5dd1addf-8f85-435b-8902-0ce5a59239fd.png)

Sorry about that, I updated with fix on release please redownload it and install it

**Comment by N367B** [comment]
> > > > 
> > > 
> > > 
> > > can try without spoof?
> > 
> > 
> > It seems to be working, except I get "Android System Intelligence keeps stopping" several times. And the select option doesn't seem to be working ![Screenshot_20211120-111440_Messages~2](https://user-images.githubusercontent.com/42220691/142722742-5dd1addf-8f85-435b-8902-0ce5a59239fd.png)
> 
> Sorry about that, I updated with fix on release please redownload it and install it

I worked fine, excpet that when I called I didn't hear anything. And still bugs with select option

**Comment by Kingsman44** [comment]
> 

I mean Device personalization service crash fix is added today. Calls are working fine here. Now on a12 select options needs system UI changes

This commit https://github.com/Project-Elixir/frameworks_base/commit/28a877f3a51e9dccf6ff330c787dbf6175a9e02b

**Comment by N367B** [comment]
> > 
> 
> I mean Device personalization service crash fix is added today. Calls are working fine here. Now on a12 select options needs system UI changes
> 
> This commit [Project-Elixir/frameworks_base@28a877f](https://github.com/Project-Elixir/frameworks_base/commit/28a877f3a51e9dccf6ff330c787dbf6175a9e02b)

I'm not a dev so I don't know what to do with that 😆. And the select option was working fine when the device was spoofed. Thanks for the response

**Comment by N367B** [comment]
I reinstalled it, this time without any backups. And it seems like I can connect to _any_ server (for now). Hope everyone have it working too.

There are still some other issues that aren't related to this thread

**Comment by N367B** [comment]
> I reinstalled it, this time without any backups. And it seems like I can connect to _any_ server (for now). Hope everyone have it working too.
> 
> There are still some other issues that aren't related to this thread

It doesn't work anymore. I don't know what to do : it's happening randomly. Need anything to solve that ?

**Comment by Kingsman44** [comment]
> 

Fixed in in 1.81

**Comment by N367B** [comment]
> > 
> 
> Fixed in 1.81

Wow, thanks. The notifications too ?

Also, not every features is working properly.

**Comment by Kingsman44** [comment]
What notifications??
Which features

**Comment by Kingsman44** [comment]
I am not facing any bugs.

Please check it here
https://github.com/Kingsman44/Pixelify/files/7594344/Pixelify-v1.81.zip

**Comment by N367B** [comment]
> What notifications?? Which features

Notifications never show up while spoofing the device.

And some features do not work properly or even at all. For example, the now playing options can't be activated. 

I will try the release and update you on that.

**Comment by N367B** [comment]
> I am not facing any bugs.
> 
> Please check it here https://github.com/Kingsman44/Pixelify/files/7594344/Pixelify-v1.81.zip

After (a bit) of testing, I can say that I can't see anything solved. At least with a spoofed device

**Comment by Kingsman44** [comment]
Now playing is pixel exclusive device. It won't on any other smart phone.

If you saying for notifications it working on I tested 3 different Android 12 roms (ARROW, AEX, FLUID) all working fine.

**Comment by Kingsman44** [comment]
[Pixelify-v1.81.zip](https://github.com/Kingsman44/Pixelify/files/7600436/Pixelify-v1.81.zip)

Please let me know, if issue exists on those one too.

**Comment by Kingsman44** [comment]
![Screenshot_20211125-112358_Pixel Launcher](https://user-images.githubusercontent.com/58323485/143387442-19c806ac-47da-4123-93be-28a4535434b0.png)

**Comment by N367B** [comment]
So, I reinstalled the module (new file), and notification and installation worked this time, so I don't know what's causing the issue.

Moreover, the select option does not work well (see video [).](https://photos.app.goo.gl/J6cV4vyWoP2XXd5K7) --> The first time I open the select option, it shows some things, but after, nothing is showing up (I have to restart the phone to show something again).

Thanks for the response about the “Now playing”

I'm on ArrowOS, Android 12

Thanks again for the great support !

**Comment by Kingsman44** [comment]
> So, I reinstalled the module (new file), and notification and installation worked this time, so I don't know what's causing the issue.
> 
> Moreover, the select option does not work well (see [video).](https://photos.app.goo.gl/J6cV4vyWoP2XXd5K7) --> The first time I open the select option, it shows some things, but after, nothing is showing up (I have to restart the phone to show something again).
> 
> Thanks for the response about the “Now playing”
> 
> I'm on ArrowOS, Android 12
> 
> Thanks again for the great support !

can check notifications and play store work in this build or not.
also recents

https://t.me/pixelifysupport/554

**Comment by N367B** [comment]
> > So, I reinstalled the module (new file), and notification and installation worked this time, so I don't know what's causing the issue.
> > Moreover, the select option does not work well (see [video).](https://photos.app.goo.gl/J6cV4vyWoP2XXd5K7) --> The first time I open the select option, it shows some things, but after, nothing is showing up (I have to restart the phone to show something again).
> > Thanks for the response about the “Now playing”
> > I'm on ArrowOS, Android 12
> > Thanks again for the great support !
> 
> can check notifications and play store work in this build or not. also recents
> 
> https://t.me/pixelifysupport/554

Ok, thanks. I'll close this issue, since it's most likely solved. I'll use telegram for futures issues, I think
