### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by AxiK101** [Kingsman44/Pixelify#255]
Device name: Xiaomi Mi 11i
Rom name: Lineage OS 20.0
Android version: 13
Pixelify version: 3.0

Bug Description: I noticed extreme battery drain after flashing this module, on battery consumption stats i see Google One VPN app and Pixel launcher to have highest persentage. Especially the VPN app, even after i force freezed it via Icebox app.

**Comment by AnimeWaifuGirl** [comment]
That's normally live wallpaper needing a lot energy
