### ISSUE TITLE
Call screening can't be heard on A12

### ISSUE THREAD

**Issue by shivam0664** [Kingsman44/Pixelify#26]
It can't be heard . 
Device:- Redmi Note 10 Pro Max
Rom:- AOSP+ by Grewal
A12
How to fix?
 And also i didn't get the latest gboard themes and smart compose

**Comment by Kingsman44** [comment]
Smart compose should be there, for latest theme you need to spoof to pixel 5

**Comment by Kingsman44** [comment]
For call screening not issue it device specific issue. I will let you know if I found out anything.

Commit I added on fixes fixed that issue on my device Redmi Note 4

**Comment by shivam0664** [comment]
It's spoofed to Pixel 5 but it's still the same gboard. Thanks for replying though. Really cool module btw.

**Comment by Kingsman44** [comment]
As this is duplicate issue, I am closing this

for future reference comment on this https://github.com/Kingsman44/Pixelify/issues/12
