### ISSUE TITLE
Add Support for Nothing OS

### ISSUE THREAD

**Issue by spike0en** [Kingsman44/Pixelify#263]
Optimizing and refining the module to work seamlessly on stock Nothing OS for Nothing Devices like Phone 1 and 2 would be appreciated!

**Comment by thesmart1** [comment]
From my personal testing on Nothing ph(1) Pixelify works great on NothingOS.

**Comment by DavidScann** [comment]
Running Pixelify on NOS 2.5.1 on a Phone (2) works great
