### ISSUE TITLE
Can't install dialer apk

### ISSUE THREAD

**Issue by milindpatel63** [Kingsman44/Pixelify#27]
I am getting the following error when installing the dialer apk you provided...
app not installed as package appears to be corrupt

**Comment by milindpatel63** [comment]
Also, is there a way to get only the pixel launcher 12 from this module...i only want the launcher feature, but after installing this module, my safety net fails...i have installed pixel 6 props currently to pass safety net..

**Comment by Kingsman44** [comment]
I removed fingerprint spoof, i don't think my module effect the CTS.

**Comment by Kingsman44** [comment]
There might be other for pixel launcher ig.

**Comment by Kingsman44** [comment]
> I am getting the following error when installing the dialer apk you provided... app not installed as package appears to be corrupt

I think it working, rename .zip to .apk if downloaded in zip.
Though I will recheck it.

**Comment by milindpatel63** [comment]
> I removed fingerprint spoof, i don't think my module effect the CTS.

your module doesn't affect CTS....
arrow os 12 fails CTS by default, and fix for that is magisk hide with pixel 6 props.....and your zip spoofs pixel 5, so my CTS fails...
although now you say you have disabled CTS.. I'll retry again...

**Comment by Quantizr** [comment]
> I am getting the following error when installing the dialer apk you provided... app not installed as package appears to be corrupt

Make sure you uninstall the old version before you try installing the new one.

However, I am able to install the dialer apk, but it tells me "The device is not supported and phone calls may not work correctly"

**Comment by Kingsman44** [comment]
> > I am getting the following error when installing the dialer apk you provided... app not installed as package appears to be corrupt
> 
> Make sure you uninstall the old version before you try installing the new one.
> 
> However, I am able to install the dialer apk, but it tells me "The device is not supported and phone calls may not work correctly"

This will be fixed on next version, sorry for inconvenience

**Comment by Kingsman44** [comment]
> > I am getting the following error when installing the dialer apk you provided... app not installed as package appears to be corrupt
> 
> Make sure you uninstall the old version before you try installing the new one.
> 
> However, I am able to install the dialer apk, but it tells me "The device is not supported and phone calls may not work correctly"

Well, it actually needs Pixel Experience 2021 Flag, but adding it will break Google Photos edit stuff.
