### ISSUE TITLE
No audio in calls at all on apollon (Mi 10T Pro)

### ISSUE THREAD

**Issue by breadtard** [Kingsman44/Pixelify#28]
As the title says, no audio at all when calling on apollon.
I cant hear the caller, the caller cant hear me.
Even if i *dont* install the caller features, they still get installed and audio breaks

rom: ArrowOS Android 12 experimental

**Comment by Kingsman44** [comment]
this will be fixed on next build

**Comment by Kingsman44** [comment]
It should work now on v1.8, if doesn't feel free reopen or create new issue
