### ISSUE TITLE
Pixel 5 Spoofing now breaks safetynet as in Pixelify 1.71 

### ISSUE THREAD

**Issue by usrDottik** [Kingsman44/Pixelify#29]
Spoofing your device to a Pixel 5 to enable special functions such as, Adaptive Sound, New Generation Assistant, etc. Makes ctsProfile check fail, I have tested this in a CustomROM, DotOS, spoofing to my correct fingerprint made it pass again, but features are now shorter, tested with Pixelify 1.71, I will try it with 1.7 and see if it happens.

UPDATE: I got it to work with Pixelify 1.71 spoofing props to Pixel 5 in MagiskHide Props Config + Force BASIC key attestation on it for Pixel 6.

UPDATE2: I actually got it to work by modifying system.prop and setting the device model to be a Pixel 6, I got the old edit wrong, sorry

**Comment by usrDottik** [comment]
Safety-net with Pixelify 1.7 is working correctly!!! I hope this helps somehow 
![Screenshot_20211110-164859_YASNAC](https://user-images.githubusercontent.com/81375555/141183097-af849f54-a0aa-4547-86a2-f16e75fb5ebc.png)
!

**Comment by Kingsman44** [comment]
> Safety-net with Pixelify 1.7 is working correctly!!! I hope this helps somehow ![Screenshot_20211110-164859_YASNAC](https://user-images.githubusercontent.com/81375555/141183097-af849f54-a0aa-4547-86a2-f16e75fb5ebc.png) !

Working here, well my device is very old. Safetynet always pass. I will what I can doo
