### ISSUE TITLE
Minor issues on Pixel 2 XL(Taimen) Stock ROM

### ISSUE THREAD

**Issue by siddharthalodha** [Kingsman44/Pixelify#3]
I tried the latest mod on Stock Pixel 2 XL ROM. 
1. Call recording doesn't work properly. Sometimes, it appears as recording failed and in some cases, even though it says it's recording, can't access the recording after the call unlike the Call Screen Recording. 
2. Also, i tried setting up a con-call yesterday, there were some issues while merging calls. Not sure, if it is due to this module.
3. Now Playing stops working unless I delete following files from the module :
/system/etc/firmware/ 
music_detector.sound_model
music_detector.descriptor

Can you make this an option while installing the module, so that I can skip it. Thanks. 

4. Adaptive Sound has stopped appearing in the menu latest version. It was working fine before the re-write. 

Thanks. Let me know if you need more info.

**Comment by siddharthalodha** [comment]
Also, it never starts downloading any files from module(Like Live wallpapers/NGA files) as it says internet not found even though I am connected. You can probably check that too if that's working.

**Comment by Kingsman44** [comment]
> I tried the latest mod on Stock Pixel 2 XL ROM.
> 
> 1. Call recording doesn't work properly. Sometimes, it appears as recording failed and in some cases, even though it says it's recording, can't access the recording after the call unlike the Call Screen Recording.
> 2. Also, i tried setting up a con-call yesterday, there were some issues while merging calls. Not sure, if it is due to this module.
> 3. Now Playing stops working unless I delete following files from the module :
>    /system/etc/firmware/
>    music_detector.sound_model
>    music_detector.descriptor
> 
> Can you make this an option while installing the module, so that I can skip it. Thanks.
> 
> 1. Adaptive Sound has stopped appearing in the menu latest version. It was working fine before the re-write.
> 
> Thanks. Let me know if you need more info.

1) Call Recording is in beta, that's why never written in change logs.
2) I don't think it depends on model.
3) Ok, I will remove this files.

**Comment by siddharthalodha** [comment]
Just an update. I switched to ProtonAOSP for some time.
1. Call recording works perfectly in this ROM.
2. Haven't tried the con-call feature
3. Now playing doesn't work because of above mentioned reason.
4. Adaptive Sound appears in this ROM.
5. Also, internet download for Pixel live wallpapers/NGA work in this ROM.

One thing i have observed is that Gboard customizations have stopped working. Even gboard NGA has been gone for quite some time which was working fine earlier, not sure if it is a server side thing from Google.

**Comment by Kingsman44** [comment]
> Just an update. I switched to ProtonAOSP for some time.
> 
> 1. Call recording works perfectly in this ROM.
> 2. Haven't tried the con-call feature
> 3. Now playing doesn't work because of above mentioned reason.
> 4. Adaptive Sound appears in this ROM.
> 5. Also, internet download for Pixel live wallpapers/NGA work in this ROM.
> 
> One thing i have observed is that Gboard customizations have stopped working. Even gboard NGA has been gone for quite some time which was working fine earlier, not sure if it is a server side thing from Google.

Looks like some call recording overlays are missing.
I will add soon

**Comment by Kingsman44** [comment]
All problems fix had been added in module. So I am closing this now, if you face any other or any same problem you create new issue.
