### ISSUE TITLE
S10 lite stucks on Samsung logo

### ISSUE THREAD

**Issue by MEZHH** [Kingsman44/Pixelify#31]
Hi. I have installed it on my S10 lite. The phone stucks on Samsung logo

**Comment by Kingsman44** [comment]
Custom rom or stock rom?

**Comment by MEZHH** [comment]
Stock rom

**Comment by Kingsman44** [comment]
can try on this version, it working or not ?
https://drive.google.com/file/d/1CqOzG5UjmapY5vBTvQWaqaZ-kXzXZAl6/view?usp=sharing

**Comment by MEZHH** [comment]
I  installed it and the phone boots normally. But nothing is changed on the phone. 

![Screenshot_20211118-102756_Photos](https://user-images.githubusercontent.com/40662103/142364079-492da13f-41ca-4693-b444-6efbce5dcd94.jpg)

**Comment by Kingsman44** [comment]
> I installed it and the phone boots normally. But nothing is changed on the phone.
> 
> ![Screenshot_20211118-102756_Photos](https://user-images.githubusercontent.com/40662103/142364079-492da13f-41ca-4693-b444-6efbce5dcd94.jpg)

Samsung Stock Right? Do you spoof to Pixel 5?

**Comment by MEZHH** [comment]
Yes, I spoofed to Pixel 5

![Screenshot_20211118-104557_Settings](https://user-images.githubusercontent.com/40662103/142366076-14831e52-4207-43e8-9bc8-c8649aa6bb5d.jpg)

**Comment by Kingsman44** [comment]
try clear data of Google Photos app

**Comment by MEZHH** [comment]
I have checked again Magic Eraser works, but I can't see any other changes

**Comment by MEZHH** [comment]
> try clear data of Google Photos app

I have tried, result is the same

**Comment by Kingsman44** [comment]
if want call screening then install Google Dialer, reinstall module. if already installed then make it default app and restart

**Comment by MEZHH** [comment]
another error I got

![Screenshot_20211118-104952_Phone](https://user-images.githubusercontent.com/40662103/142366461-33b55b8c-1920-453c-91bf-201cbe43d83a.jpg)

**Comment by MEZHH** [comment]
> if want call screening then install Google Dialer, reinstall module. if already installed then make it default app and restart

Actually I need only "Unlimited storage"

**Comment by Kingsman44** [comment]
> another error I got
> 
> ![Screenshot_20211118-104952_Phone](https://user-images.githubusercontent.com/40662103/142366461-33b55b8c-1920-453c-91bf-201cbe43d83a.jpg)

Please ignore it, it need PIXEL 2021 Experience feature file. As you are using pixel 6 google dialer. if i add PIXEL 2021 Experience it will break google photos editing due to missing feature, to remove it you can use pixel 5 google dialer

**Comment by Kingsman44** [comment]
> > if want call screening then install Google Dialer, reinstall module. if already installed then make it default app and restart
> 
> Actually I need only "Unlimited storage"

wait about hour, i give you one build with unlimited storage

**Comment by MEZHH** [comment]
This is my log, if you need.


- Copying zip to temp directory
- Installing Pixelify-v1.8.zip
- Device is system-as-root
Archive:  /data/user/0/pyu.gulwsu.o/cache/flash/install.zip
  inflating: module.prop
***************
 Pixelify 
 by Kingsman44 
***************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/pyu.gulwsu.o/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/pyu.gulwsu.o/cache/flash/install.zip
  inflating: LICENSE
  inflating: README.md
   creating: addon/
  inflating: addon/aapt
  inflating: addon/curl
  inflating: addon/dumpsys
  inflating: addon/keycheck
  inflating: config.prop
  inflating: customize.sh
  inflating: deviceconfig.txt
   creating: files/
  inflating: files/PixelThemesStub.apk
  inflating: files/PixeliflyDPS.apk
  inflating: files/PixelifyWallpaper.apk
  inflating: files/com.google.android.dialer
  inflating: files/flip-30.tar.xz
  inflating: files/flip-31.tar.xz
  inflating: files/flip.tar.xz
  inflating: files/nga.xml
  inflating: files/pl-29.tar.xz
  inflating: files/pl-30.tar.xz
  inflating: files/pl-31.tar.xz
  inflating: files/system.tar.xz
  inflating: files/tur.tar.xz
  inflating: module.prop
  inflating: recording.txt
  inflating: sepolicy.rule
  inflating: service.sh
  inflating: spoof.prop
  inflating: system.prop
  inflating: uninstall.sh
mkdir: can't create directory '/sdcard/Pixelify': File exists
mkdir: can't create directory '/data/adb/modules_update/Pixelify/system/product/priv-app': File exists

- Detected Arch: arm64
- Detected SDK : 30
- Detected Ram: 5582752

- Vol Key Test
    Press a Vol Key:

- Installing Pixelify Module
- Extracting Files....

  Do you want to Spoof your device to Spoof your device to Pixel 5 ( raven )?
   Vol Up += Yes
   Vol Down += No

  Selected: Volume UP


  Do you want to install Google Dialer features?
   - Includes Call Screening, Call Recording, Hold for Me, Direct My Call
   (For all Countries)
    Vol Up += Yes
    Vol Down += No

  Selected: Volume UP

- Enabling Call Screening & Hold for me & Direct My Call

- Please Use google Dialer apk for
  Direct my Call given in Pixelify github link
 
- Enabling Call Recording (Working is device dependent)
 
- Please set your launguage to
  English (United States) for call screening
 

- Google Dialer is not installed as a system app !!
- Making Google Dialer as a system app

  Google is installed.
  Do you want to installed Next generation assistant?
   Vol Up += Yes
   Vol Down += No

  Selected: Volume UP

- Installing NgaResources from backups

  (Network Connection Needed)
  Do you want to install and Download Pixel LiveWallpapers?
  Size: 108 Mb
   Vol Up += Yes
   Vol Down += No

  Selected: Volume Down

  Do you want to install PixelBootanimation?
   Vol Up += Yes
   Vol Down += No

  Selected: Volume Down

  Do you want to install Pixel Launcher?
   Vol Up += Yes
   Vol Down += No

  Selected: Volume Down

  Do you want to install Extreme Battery Saver (Flipendo)?
    Vol Up += Yes
    Vol Down += No

  Selected: Volume UP

- Installing Extreme Battery Saver (Flipendo)
chmod: /data/adb/modules_update/Pixelify/system/vendor/overlay/*.apk: No such file or directory

- Done

- Replace target: /system/system_ext/priv-app/Flipendo
- Installing custom sepolicy rules
- Sepolicy rules dir is /dev/7crw/.magisk/mirror/cache
rmdir: '/data/adb/modules_update/Pixelify': Directory not empty
- Done

**Comment by Kingsman44** [comment]
alright, does extreme battery saver showing in settings > battery ?

**Comment by MEZHH** [comment]
> alright, does extreme battery saver showing in settings > battery ?

No it doesn't. It's just Samsung's battery saving 


![Screenshot_20211118-110500_Device care](https://user-images.githubusercontent.com/40662103/142368295-7a79c998-26e4-41ba-8f64-5b9ac2ce84ac.jpg)

**Comment by Kingsman44** [comment]
i think it is installed, but not shown in settings. can try to see with Activity launcher?

**Comment by MEZHH** [comment]
![Screenshot_20211118-111223_Activity Launcher](https://user-images.githubusercontent.com/40662103/142369147-c9170bd6-6926-4fa2-a91a-dbbf5ecc2670.jpg)

**Comment by Kingsman44** [comment]
alright, thank so it can't be used if another battery saver is enabled.

**Comment by Kingsman44** [comment]
try this one, https://drive.google.com/file/d/1CqOzG5UjmapY5vBTvQWaqaZ-kXzXZAl6/view?usp=sharing

select Pixel spoof, after installation Clear Data Photos, wait until it set it your photos

**Comment by Kingsman44** [comment]
tried just now, it works here. I upload 500Mb video and it does not count to storage.

**Comment by Kingsman44** [comment]
![Screenshot_20211118-132324_Photos~2](https://user-images.githubusercontent.com/58323485/142375118-01051c4c-98b9-4ef7-b432-3dcf0d1c020f.png)

**Comment by MEZHH** [comment]
I have installed it. I'll try and write here the result

**Comment by Kingsman44** [comment]
Well, bootloop for your device is solved. so i am closing this issue.

if face any problem feel free to reopen or create or comment on existing issue
