### ISSUE TITLE
Live caption - more languages

### ISSUE THREAD

**Issue by Veganizer** [Kingsman44/Pixelify#314]
Is there a way to add more languages to live caption?
I think that google restricted it in the tts service. But in the google pixels more languages are available.

It is duplicated to: https://github.com/Kingsman44/Pixelify/issues/184

Just with enhancement label.

**Comment by Fede2782** [comment]
Since a few months ago Live Captions are available to every Android 12+ device in the following languages: Italia, English, French, Spanish, German, Hindi and Japanese

**Comment by Veganizer** [comment]
Why can't I choose it then? Do I install the false version of Google TTS?

**Comment by Fede2782** [comment]
Live Captions are managed by Android System Intelligence component. Check it is working and up to date

**Comment by Veganizer** [comment]
fixed it, I installed TTS by aurora store. It seems to be a old version. If i install it by sideload of the AOSP, I got subtitles in other languages. Will close it :-)
