### ISSUE TITLE
3.1 alpha download links?

### ISSUE THREAD

**Issue by zelenooki87** [Kingsman44/Pixelify#316]
Hi. Where I can get 3.1 alpha links for module and submodules? 
Thanks

**Comment by Fede2782** [comment]
https://mega.nz/folder/socjGTJK#XdK2sDYoUdAX8VSPbFbgSA

I built Pixelify v3.1-alpha (alpha branch) from source. This is a build zip. It is an alpha so there may be issues. there is the source i used included (d2f55b62f1af8f291b0248987bf004634661fcac commit of alpha branch). Riru build is broken so it is not included.

**Comment by zelenooki87** [comment]
Could you share submodule for google photos only(I am particularily mostly interested for it)
latest official was
Google-Photos-Features-Unlimited-backup.zip | v2 |   | 4142 | 2023-11-13 | 88.40 MB
Or tell me if there are no changes in alpha for this module?
Thanks

**Comment by Fede2782** [comment]
> Could you share submodule for google photos only(I am particularily mostly interested for it) latest official was Google-Photos-Features-Unlimited-backup.zip | v2 |   | 4142 | 2023-11-13 | 88.40 MB Or tell me if there are no changes in alpha for this module? Thanks

Submodule are not part of the main source. Probability they are built manually so i have no way to do it.

**Comment by zelenooki87** [comment]
Thanks. Closing issue.
