### ISSUE TITLE
Android System Intelligence and Style And Wallpaper programs crash

### ISSUE THREAD

**Issue by PianCat** [Kingsman44/Pixelify#32]
Devices: OnePlus 7 Pro
ROM: ArrowOS 12.0

I can't use Android System Intelligence and Style and Wallpaper programs properly, [here is log](https://raw.githubusercontent.com/PianCat/APTSSF/main/Pixelify_CrashLog/crashlog.log)
Also I would like to ask how to enable Next Gen Google Assistant

**Comment by Kingsman44** [comment]
Are issues were fixed?

**Comment by PianCat** [comment]
Fixed
