### ISSUE TITLE
Pixelify with ZygiskNext

### ISSUE THREAD

**Issue by paaipoi** [Kingsman44/Pixelify#330]
Device name: Redmagic 8 Pro
Rom name: Redmagic OS 8.0.2
Android version: A14
Pixelify version: 3.0

Bug Description: pixelify does not detect zygisk when using zygisk next (standalone implementation), but pixelify works perfectly using build-in zygisk

 ZygiskNext version: 1.0.6-2

**Comment by paaipoi** [comment]
edit: solved by using zygisknext by admirepowered, it also solved the "zygisk not detected" red font present in the original zygisknext

**Comment by ItzKazuki** [comment]
Hello, same problem here, any recommendations for zygisk next? I'm change to zygisk next bh adminrepowered and doesn't working
