### ISSUE TITLE
Google photos doesn't backup unlimitedly

### ISSUE THREAD

**Issue by Teeteegithub** [Kingsman44/Pixelify#34]
Flash the latest one. Google photos backups towards my drive.

**Comment by Kingsman44** [comment]
Which ROM? Which Device?
Make sure you spoofed to pixel 5 and also You have selected Storage Saver quality

**Comment by Teeteegithub** [comment]
I'm running Poco F2 Pro on Pixel Expérience, always choose Pixel 5 & storage saver ofc. After asking around a lot it seems the problem persists on other a12 ROM as well :(

**Comment by Kingsman44** [comment]
Well problem is in Pixel Experience it internally spoof device to pixel 6 pro to google apps which pixelify can't override.

Because of that even in spoofing device to pixel 5 for photos it recognises it as pixel 6 pro hence unlimited storage won't work.

**Comment by zainullahk** [comment]
im on pixel experience and i used lsposed module
it says pixel 5 but no free backup :(
also same on lineage and arrow

**Comment by Kingsman44** [comment]
If you used lsposed module that's for unlimited original and pixelify v1.81 gives unlimited storage saver surely they conflict.

Also testing is going on it should be released very soon next update.

Also next update already have option for unlimited original quality that can fix your issue
