### ISSUE TITLE
Device Apps are being replace but not restored back

### ISSUE THREAD

**Issue by being-yash-t** [Kingsman44/Pixelify#35]
This module replaces the existing apps in the system (Like styles, pixel launcher, dialer) but doesn't restore them when a feature is turned off or when the module is removed from magisk.

I used this module and tuned on styles by the module when I did a reboot, the money engine's colour palette  didn't show up 
(even after I cleared data for styles app)
When I removed the module There was no styles app installed on my device, I couldn't even change wallpaper.

This shouldn't happen in magisk, system-less right?
Any possible way to fix this? without using this module

**Comment by Kingsman44** [comment]
It shouldn't happen. Idk the reason why it removes. I need to check it.

**Comment by being-yash-t** [comment]
@Kingsman44 The apps don't restore after reflashing the ROM, nor after removing magisk
After reflashing the ROM the apps should come back, but that's not the case

Here something different is going on.

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2

feel free to reopen or create new issue if doesn't
