### ISSUE TITLE
Motorized popup camera stops working on op 7t pro

### ISSUE THREAD

**Issue by wacko1805** [Kingsman44/Pixelify#37]
My front popup camera mechanism stops working when this module is flashed.  The camera still works, just doesn't popup on my OnePlus 7t pro.

**Comment by Kingsman44** [comment]
Can send logs?

**Comment by Kingsman44** [comment]
Does it works without spoofing?

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2 Use zygisk and magisk v24+

feel free to reopen or create new issue if doesn't
