### ISSUE TITLE
Call recording removed from 1.81

### ISSUE THREAD

**Issue by gerardovasquez307** [Kingsman44/Pixelify#38]
I use the module without pixel spoofing and only the Google dialer features. I have tested multiple permutations of 1.81 with different versions and cannot get call recording. I then reverted to 1.8 and call recording was returned with beta and stable versions of the Google dialer app. Can you please return the call recording feature without spoof in the latest version? Thank you

Oneplus 9 oxygen os 11

**Comment by Kingsman44** [comment]
Working here, still i will check

**Comment by Kingsman44** [comment]
![Screenshot_20211222-200100_Phone](https://user-images.githubusercontent.com/58323485/147108324-6e783343-f4f0-4971-911d-e667dbc9913b.png)

**Comment by gerardovasquez307** [comment]
Doesn't work for me. Believe me I checked all types of combinations and was not able to get call recording to work on 1.81.it instantly came back going to version 1.8

**Comment by Kingsman44** [comment]
Alright, i will try to fix it.

**Comment by Kingsman44** [comment]
This is fixed on v1.9

**Comment by gerardovasquez307** [comment]
Confirmed thank you!
