### ISSUE TITLE
Google Pixel 4 launcher crash!!!

### ISSUE THREAD

**Issue by zyh941** [Kingsman44/Pixelify#39]
Hi, 
I am a new Pixel 4 (running 2021-12 stock Android 12) user, yesterday I selected installing the new Pixel Launcher during installation of Pixelify, it succeed and completely replaced by the new version of Pixel launcher. 

But accidently, when I uninstalled Pixelify and reboot, my phone stuck on home screen and can not run normally, and I found the Pixel launcher was not the normal original version in system settings. I tried to install the latest version of launcher but not work ( it showed Pixel launcher is crashed and stopped ).That is, Pixelify destroyed completely my Pixel launcher!  Please fix this severe problem and give me a chance to do this: uninstall Pixelify completely and keep current normal Pixel launcher not changed.

**Comment by Kingsman44** [comment]
This will be fixed on new update.

Reason is because of module didn't updated pl for dec patch

**Comment by zainullahk** [comment]
> This will be fixed on new update.
> 
> Reason is because of module didn't updated pl for dec patch

any eta for this patch? 
as after some time the jan patch will release so  iwant to know how long i can update

**Comment by zainullahk** [comment]
> This will be fixed on new update.
> 
> Reason is because of module didn't updated pl for dec patch

its been 11 days and jan patch for pe has already released and i really want to uninstall this module as jan patch adds unlimited gphotos but it might break cause of this module 
so again ( ik askign eta is not good) but any eta?

**Comment by Kingsman44** [comment]
I apologise for inconvenience, updating of module is going, you try new beta version with lots of fixes in telegram. But I think it should be release in 1-2 days

**Comment by zainullahk** [comment]
Ok I'll try one in telegram

**Comment by zainullahk** [comment]
> I apologise for inconvenience, updating of module is going, you try new beta version with lots of fixes in telegram. But I think it should be release in 1-2 days

can you send telegram link
thanks in advance

**Comment by zainullahk** [comment]
> > I apologise for inconvenience, updating of module is going, you try new beta version with lots of fixes in telegram. But I think it should be release in 1-2 days
> 
> can you send telegram link thanks in advance

same issue on beta build :(

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2

feel free to reopen or create new issue if doesn't
