### ISSUE TITLE
Volume Key issue

### ISSUE THREAD

**Issue by maharshi18** [Kingsman44/Pixelify#40]
Hi,
I am trying to flash this on windows subsystem for android, Windows volume key shortcuts are not working during installation. is there anything which i can do?

**Comment by Kingsman44** [comment]
Does Windows subsystem have same type of storage like android phone?

Like to disable it i gonna create a file which stores all options to set true or false.

Does /sdcard exist on windows subsystem?

**Comment by maharshi18** [comment]
Not 100% sure about the storage thing, but there is file explorer and stuff available there which is similar to phone. I can create and modify files from google files app in WSA.

not sure about the path so can't comment on /sdcard directory.

**Comment by Kingsman44** [comment]
ok, so i adding file inside the zip module only you need to extract and change file configuration and rezip it. is this ok with you?

**Comment by maharshi18** [comment]
Currently i don't have any windows 11 machine to try that out, but yeah it should work. Thanks.

**Comment by Kingsman44** [comment]
This is fixed v1.9
