### ISSUE TITLE
removes material you option after flashing

### ISSUE THREAD

**Issue by zainullahk** [Kingsman44/Pixelify#42]
i flashed this and i love it one issue tho this breaks material you (pixel expereince) material you works but i  cant configure it after installing this module

**Comment by Kingsman44** [comment]
Huh? Strange, no Material You breaking here on fluid also people had tried on different rom like pixel stock, PE Rom also no one report this.

Try without installing Google Styles and Wallpaper

**Comment by zainullahk** [comment]
Material you works
But the styles and wallpapers app has no option to change it

**Comment by Kingsman44** [comment]
Huh? You mean change colours?
![Screenshot_20220108-202805_Wallpaper   style](https://user-images.githubusercontent.com/58323485/148648965-572f354a-4fe2-4f36-9509-cf6e8b4ce8f7.png)

**Comment by zainullahk** [comment]
That does not exist for me
Can you send me the apk of wallpaper app with apk extractor?
Also if I uninstall the module pixel launcher keeps crashing and won't work

**Comment by zainullahk** [comment]
Also if I uninstall the module pixel launcher keeps saying not responding
and it won't work and wallpapers app uninstalls if I reflash the module
pixel search is broken and can only search apps and wallpapers app is gone
and when I install it it has no material you option also g photos does not
work it says it's backing up for free but it's actually consuming storage
this is spoofed as pixel 5

**Comment by Kingsman44** [comment]
not responding or crashing??

Update Google Private compute services from playstore to fix search....
This one https://play.google.com/store/apps/details?id=com.google.android.as.oss

**Comment by zainullahk** [comment]
It works now
But pixel search is still broken :(

**Comment by zainullahk** [comment]
but i cant uninstall the module it says pixel launcher not responding please help :(

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2

feel free to reopen or create new issue if doesn't
