### ISSUE TITLE
Wallpaper app deleted

### ISSUE THREAD

**Issue by nonyonah** [Kingsman44/Pixelify#44]
Hey, I installed this module plus the launcher that came with it but i uninstalled it later and then found that my wallpaper app is gone... It comes back whenever I install module. What's going on here? Help me fix it please

**Comment by laltroweb** [comment]
Same here.
Also if I install via store, isn't ok (need to be system app).
If I try to reinstall also without more setting (eg, no dialer recording etc), at reboot i still see call recording enabled.

So, here do not work (i can change switch, but seems to install everything every time), and if I uninstall remove also launcher, wallpaper... So bad.

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2

feel free to reopen or create new issue if doesn't
