### ISSUE TITLE
This warning appears every single time I open the phone app is there any way to remove that

### ISSUE THREAD

**Issue by diosvany** [Kingsman44/Pixelify#45]
Noted.

**Comment by Kingsman44** [comment]
Use Google Dialer version which doesn't contain 2021prefix
Use can use this apk. https://www.apkmirror.com/apk/google-inc/google-phone/google-phone-74-0-424204618-release/

Also it's better hide phone number on screenshots you send so no one may misuse it.

**Comment by diosvany** [comment]
It stopped working

**Comment by diosvany** [comment]
Do i have to reinstall the magisk module

**Comment by diosvany** [comment]
How come that phone dialer doesn't have direct call activated
