### ISSUE TITLE
Google detects my device as Pixel 5 although I chose Pixel 6 Pro while installing module

### ISSUE THREAD

**Issue by ITZBoudy** [Kingsman44/Pixelify#46]
Google detects my device as Pixel 5 although I choose Pixel 6 Pro while installing module
![Screenshot_20220201-192351_Pixel Launcher~2](https://user-images.githubusercontent.com/82240928/152021486-c434ad35-873b-4d55-a2cc-4d5588b72607.png)

**Comment by Kingsman44** [comment]
Which custom rom?

**Comment by ITZBoudy** [comment]
Pixel Experience Android 12

> Which custom rom?

**Comment by Kingsman44** [comment]
It's not Pixelify Issue.

It your Android Custom Feature. Your Rom internally make Google gms to recognise Pixel 6 Pro to get some pixel features and monet theming.

Even though you didn't selected any Pixel spoof from Pixelify. Your device will be recognised as Pixel 6 Pro.

Here is function of code which executes via zygote.
https://github.com/PixelExperience/frameworks_base/blob/371955323c9a53ee9745e44286c155935e007b70/core/java/com/android/internal/util/custom/PixelPropsUtils.java
