### ISSUE TITLE
Assistant and "Hey/Ok Google" hotwords doesn't work after a restart.

### ISSUE THREAD

**Issue by hectorviov** [Kingsman44/Pixelify#48]
Pixel launcher, themes and everything else is working perfectly. But every time I restart my phone I can't use the assistant neither by launching it manually on the phone or with the hotwords. What I need to do is change the default assistant app to "None" and then back to "Google" and re-enable voice match and it works perfectly after that.

**Comment by Kingsman44** [comment]
I apologize for the problem, it is fixed now, you will get it via next update

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2

feel free to reopen or create new issue if doesn't
