### ISSUE TITLE
Google photos origional quality no longer works. 

### ISSUE THREAD

**Issue by Rihcus** [Kingsman44/Pixelify#49]
As of Feb 5th I noticed google photos started counting original quality photos when using pixelify's original quality option. I am using google photos version 5.75.0.424739917. This occurs despite the google photos app stating unlimited original quality photos are present. Not sure if this is related to Pixel 3XL losing support for unlimited original quality photos (tested on onplus 8).

![Screenshot_20220206-002525_Photos~2](https://user-images.githubusercontent.com/30292597/152668817-6b12d27b-2348-4fa3-ba28-9acfb4846131.png)

**Comment by Kingsman44** [comment]
Fixed, you will get it working via next update

**Comment by Kingsman44** [comment]
it related to pixel 3 losing support only !!, as we did spoof to p3 but using p1 configs. As Google also check model before it returns true but after update it returns false.

**Comment by Kingsman44** [comment]
also Fixed version is available in v2-beta-1 which can be found in Pixelify telegram group
Note: magisk v24+ required

**Comment by Rihcus** [comment]
> also Fixed version is available in v2-beta-1 which can be found in Pixelify telegram group Note: magisk v24+ required

Is it possible to spoof pixel 5 or 6 while keeping unlimited original quality photos say with magisk zygisk?

**Comment by Kingsman44** [comment]
yes
