### ISSUE TITLE
No download link for version 1.4

### ISSUE THREAD

**Issue by nonyonah** [Kingsman44/Pixelify#5]
There's no download link for version 1.4, is it a mistake or decided to leave it like that? And please add pixel theming

**Comment by Kingsman44** [comment]
Soon it will be added after some update and what do mean by pixel therming?

**Comment by nonyonah** [comment]
Sorry, i meant pixel theme. it isn't available in the module

**Comment by Kingsman44** [comment]
Module Already contains some Pixel Ui overlay. Ringtones, Boot Animation, Font.

Sorry, but still don't get it Pixel Theme.
If you are elaborate what's missing i might able to add it. ;)

Release had been done for V1.4 now

**Comment by nonyonah** [comment]
I meant this
![Screenshot_20210718-122925](https://user-images.githubusercontent.com/53056536/126065371-8a47bf25-7bae-4164-b378-873c9fa3ad71.png)

**Comment by Kingsman44** [comment]
Ohh, it is present with Live Wallpapers

**Comment by nonyonah** [comment]
I couldn't find that option the last time. It was just wallpaper and grid options in the styles app
