### ISSUE TITLE
Home Gesture

### ISSUE THREAD

**Issue by XMAN3650** [Kingsman44/Pixelify#51]
How can I uninstall? After I installed I lost the ability to use my home Gesture and recent apps

**Comment by XMAN3650** [comment]
deleting the module does not fix it as well..

**Comment by XMAN3650** [comment]
it also affects recent apps and even in safe mode. I'm going to go insane

**Comment by laltroweb** [comment]
Same here. Deleting delete also launcher so, home button do not work. Reinstall Pixel launcher is not sufficient (isn't a system app). So, atm can be fixed with lawchair launcher installed via magisk.

**Comment by XMAN3650** [comment]
thank you thank you thank you

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2

feel free to reopen or create new issue if doesn't
