### ISSUE TITLE
Recorder works but doesn't get any audio

### ISSUE THREAD

**Issue by hectorviov** [Kingsman44/Pixelify#54]
Google recorder app works and starts "recording" fine, but it doesn't get any audio. Is there any way to share logs or anything that could be helpful? I'm using a Oneplus 7T (hotodogb) with Yaap rom.

**Comment by Kingsman44** [comment]
![Screenshot_20220212-010434_Recorder](https://user-images.githubusercontent.com/58323485/153657735-573dc22c-b2e1-4e76-b08e-e03baaf0372d.png)

Select Audio to always use microphone.

**Comment by hectorviov** [comment]
Nice, that was it. Transcript doesn't work?

**Comment by Kingsman44** [comment]
It does works on all languages present in menu
Try clear data of Google Recorder.
![Screenshot_20220212-090105_Recorder](https://user-images.githubusercontent.com/58323485/153695122-0383bea7-d6c2-4792-9f26-1b67012dc6aa.png)

**Comment by Kingsman44** [comment]
also try clear data of Google TTS

**Comment by Kingsman44** [comment]
To fix Google Recorder in your case.

Go to Google> settings> voice> offline speech recognition>

Uninstall updates of English US.
