### ISSUE TITLE
Improper display resolution detection for bootanimation

### ISSUE THREAD

**Issue by Prasoon-kushwaha** [Kingsman44/Pixelify#55]
I have recently flashed pixelify v2 on micromax in1b with 720p display resolution but pixelify has detected it as 1080p device and flashed 1080p bootanimation.

**Comment by Kingsman44** [comment]
Can send your bootanimation zip file original?

**Comment by Prasoon-kushwaha** [comment]
https://drive.google.com/file/d/1u-ViQ1IL4kejEoKOQVL57PJWlrFZOnEA/view?usp=drivesdk

I guess old pixelify boot animation ( 1080p ) is creating issue 🤔

**Comment by Kingsman44** [comment]
Yes, remove module and reinstall module

**Comment by Prasoon-kushwaha** [comment]
After doing so stock bootanimation appears

Previously 
![IMG_20220212_224633_013.jpg](https://user-images.githubusercontent.com/73454209/153721201-2b40a42f-eec7-4de1-ad3d-8b3782f68e27.jpg)

Now

![IMG_20220212_224635_768.jpg](https://user-images.githubusercontent.com/73454209/153721221-337e14f5-2f25-488c-9580-1c7f5be6b9d1.jpg)

**Comment by Kingsman44** [comment]
I will check it.

**Comment by Kingsman44** [comment]
This is fixed, if still facing some issues feel free to reopen this issue
