### ISSUE TITLE
No network connection detected 

### ISSUE THREAD

**Issue by Everythintechyt** [Kingsman44/Pixelify#57]
I'm installing your amazing module via Magisk 24.1 zygisk Is on and When it asks to install something with network required I click yes and It says no internet detected and I have internet that works fine Could you please fix this

**Comment by Everythintechyt** [comment]
![Screenshot_20220321-130139_YouTube](https://user-images.githubusercontent.com/99302375/160027535-72589f86-b557-4217-ba5c-153510dcf6f0.jpg)
Here's proof

**Comment by LanceDdot** [comment]
Same issue as you.

**Comment by cjs1502** [comment]
Same issue.
Lineage os 18
With zygisk enabled.

**Comment by CuteCatXiao** [comment]
Same issue
Zygisk

**Comment by 3166265725** [comment]
same issue.
Did you solve it?

**Comment by Everythintechyt** [comment]
No

**Comment by Kingsman44** [comment]
An option to force enable is network is there added, if still facing some issues feel free to reopen this issue

**Comment by Superic3dgaming** [comment]
Force enable network is also not working
