### ISSUE TITLE
Zygisk Problem

### ISSUE THREAD

**Issue by ITZBoudy** [Kingsman44/Pixelify#58]
After flashing the 2.0 update and rebooting, magisk showed that this module is suspended because zygisk isn't enabled, although I have it enabled in settings, but it tells me to reboot, I tried rebooting again didn't work, I tried disabling it and re-enabling it didn't work also
![Screenshot_20220215-145215_Pixel Launcher](https://user-images.githubusercontent.com/82240928/154058153-9f3fda08-3afe-4e92-83d1-6a680f197a1b.png)
![Screenshot_20220215-145224_Pixel Launcher](https://user-images.githubusercontent.com/82240928/154058156-6f51b1c7-6386-42df-a908-5dcc04755dad.png)

**Comment by Prasoon-kushwaha** [comment]
Patch boot.img with latest magisk and flash with adb/fastboot

**Comment by ITZBoudy** [comment]
> Patch boot.img with latest magisk and flash with adb/fastboot

I can't go on latest, it bootloop, can't it work with this version?

**Comment by Kingsman44** [comment]
it's issue with magisk, can try stable magisk?

**Comment by Atarpara** [comment]
I faced this issue. I solved via uninstalling magisk and after reinstall magisk. You can try this.

**Comment by eclipsek20** [comment]
As stated above, this is a magisk/phone compatibility issue and has nothing to do with Pixelify.
