### ISSUE TITLE
Broken system apps

### ISSUE THREAD

**Issue by gerardovasquez307** [Kingsman44/Pixelify#59]
My camera app, photos app, and clock app dissappear after installing Pixelify 2.0. Conformed it was Pixelify by reinstalling rom and enabling all magisk modules except Pixelify. Once I installed Pixelify 2.0 the above apps dissappear and other system apps like play store and settings app crash on start.

Oneplus 9 on oxygen os 12

Install log below
Pixelify 2.0
   Android Version: 31
=============
---- Installation Logs Started ----
 - Network is Online

- NGA version is 1.2
- Pixel Live Wallpapers version is 1.2
- Device Personalisation Services version is 1.7
- Pixel Launcher (31) version is 2.1

 - Device Personalisation Services is not installed or not installed as system app
 - Installing Android System Intelligence
 - Backup Detected for Device Personalisation Services
 - Installing Google Dialer features
 - Adding Country (US) patch for Call Recording and Hold for me, Direct My Call
 - Installing Next generation assistant
 - Skipping Pixel Wallpapers
 - Skipping Pixel Bootanimation
 - Skipping Pixel Launcher
 - Skipping Extreme Battery Saver (Flipendo)
 - Patching Google Fit's bools
 - Patching Google Keyboard's bools
 - Generatings permission for package: com.google.android.as.oss
 - Generatings permission for package: com.google.android.as
 - Generatings permission for package: com.google.android.apps.turbo
 ---- Installation Finished ----

22/02/18 22:48:45: Service Started
22/02/18 22:48:45: Enabling com.google.android.apps.wellbeing/com.google.android.apps.wellbeing.walkingdetection.ui.WalkingDetectionActivity
22/02/18 22:49:17: Service Finished

**Comment by Kingsman44** [comment]
It works fine here, can send crash logs of apps?

Still I don't think it can remove camera, clock, app....

**Comment by gerardovasquez307** [comment]
Also, the apps only reappear when I disable Pixelify module. But then when I try opening them, they force close. I tried backing up my system apps before flashing Pixelify and have only been able to restore gallery, clock, and calculator. Camera, play store, and settings app force close even after app + data restore

**Comment by gerardovasquez307** [comment]
So it looks like this module is breaking my gapps. I tried installing only google dialer features and it still ends up destroying all of my system apps.

**Comment by gerardovasquez307** [comment]
It might also be due to the change in package names. If you think this might help solve the issue let me know which package names you would like for me to send

**Comment by Kingsman44** [comment]
it your cts pass with pixelify? also can send ss of installation at the end?

**Comment by gerardovasquez307** [comment]
> it your cts pass with pixelify? also can send ss of installation at the end?

Passing safetynet is not a problem because I add all Google framewoeks in the deny lost of zygiskz otherwise yes I get a safetynet fail. And what do u mean ss at the end? By the way the only way to revert from this is to reinstall entire systemz as disabling module does not bring my system apps back. I am currently avoiding installing Pixelify until this issue is fixed

**Comment by Kingsman44** [comment]
This is fixed in v2.1
