### ISSUE TITLE
Call screen not appearing

### ISSUE THREAD

**Issue by Atarpara** [Kingsman44/Pixelify#60]
I am using miui 13 china beta rom. Recently I installed pixelify via magisk 24.2 it installed sucessfully but it's break miui default dailer. Call screen is not appearing make call and received call so we can't pickup and drop the phones. Completing disappear call screen. 

Logs :

Device Personalisation Services version is 1.7
- Pixel Launcher (31) version is 1.3

 - Removing GoogleCamera_6gb_or_more_ram.xml as device has less than 6Gb Ram
 - Oxygen OS or MiUI or One Ui Rom Detected
 - Dropping ro.product.vendor.name, ro.product.vendor.device, ro.product.vendor.model, ro.product.vendor.brand prop from spoof.prop
 - Installing Android System Intelligence
 - No backup Detected for Android System Intelligence
 - Network is Online
 - Downloading and installing Android System Intelligence
 - Installing Next generation assistant
 - Network is Online
 - Downloading and Installing NGA Resources
 - Making Google system app
 - Skipping Pixel Wallpapers
 - Skipping Pixel Bootanimation
 - Skipping Pixel Launcher
 - Skipping Extreme Battery Saver (Flipendo)
 - Patching Google Keyboard's bools
 - Making Google Keyboard as system app
 - Making Google TTS system app
 - Generatings permission for package: com.google.android.as.oss
 - Generatings permission for package: com.google.android.googlequicksearchbox
 - Generatings permission for package: com.google.android.apps.turbo
 ---- Installation Finished ----

**Comment by Kingsman44** [comment]
Bro, your logs doesn't show Installing of Call screening features.

looking what you send, it looks like you didn't have Google Dialer, install Google dialer and make it default and reinstall module.

you will get option like Do you want to install Google Dialer Features...

select YES.

**Comment by Atarpara** [comment]
Yes I am not installing Google dialer feature and in my phone haven't google dialer but this module breaks my miui dialer app. When I receive call or make call someone my call screen completely disappeared . 

Phone system details

MIUI ROM: 22.2.16
Android : 12
Device : aliothin(mi11x)

**Comment by Kingsman44** [comment]
Miui Dialer will be fixed, thanks for informing

**Comment by Atarpara** [comment]
Thanks. I will wait new release with miui dialer fixed.

**Comment by Kingsman44** [comment]
Fixed !
