### ISSUE TITLE
Google Photos only partially tricked 

### ISSUE THREAD

**Issue by rojona** [Kingsman44/Pixelify#61]
Just flashed this on an updated Pixel 6 to get the spoofing for unlimited storage. The app does say that the phone has unlimited storage, but uploading a video still takes up space in the cloud.

Said yes to nothing during the flashing.

**Comment by Kingsman44** [comment]
it's due to your CTS not passed, so both will be fixed on next update

**Comment by Kingsman44** [comment]
Fixed on v2.01
