### ISSUE TITLE
Doesn't pass the CTS profile match

### ISSUE THREAD

**Issue by rojona** [Kingsman44/Pixelify#62]
Just flashed this on an updated Pixel 6 and a safety net app states this. I don't know what it curtails though. Said yes to nothing during the flashing.

**Comment by Kingsman44** [comment]
This is fixed, you will get it on next update.

**Comment by PanosChtz** [comment]
Confirm this as well on my Xiaomi Redmi Note 10.
If I enable pixelify module, I fail CTS.
I disable pixelify, I pass CTS.

**Comment by Kingsman44** [comment]
This is fixed, beta with fix is available in telegram group

**Comment by Kingsman44** [comment]
Fixed !
