### ISSUE TITLE
Lineage OS 19 don't accept accent theme

### ISSUE THREAD

**Issue by DerGoogler** [Kingsman44/Pixelify#64]
![Screenshot_20220302-132151_Chrome](https://user-images.githubusercontent.com/54764558/156360882-751567d5-7640-4e38-835e-ce147c49914b.png)

**Comment by Kingsman44** [comment]
you mean monet is not applying?

**Comment by DerGoogler** [comment]
Yeah

**Comment by Kingsman44** [comment]
I used lineage too. it does work on latest beta?

can you try it?
https://t.me/pixelifysupport/16388

**Comment by DerGoogler** [comment]
I use unofficial lineage, is ported to a70q

**Comment by Kingsman44** [comment]
This is fixed.
