### ISSUE TITLE
Don't work on android 12L

### ISSUE THREAD

**Issue by Sitolam** [Kingsman44/Pixelify#66]

**Comment by hectorviov** [comment]
Can confirm, Pixel Launcher crashes and won't even let you use system gestures.

**Comment by Kingsman44** [comment]
Please check this on this beta build.
https://t.me/pixelifysupport/16388

**Comment by Sitolam** [comment]
> Please check this on this beta build.
> https://t.me/pixelifysupport/16388

Thanks.
The build works but the gboard is the old theme.
[Screenshot_20220313-093440_GitHub.png](https://user-images.githubusercontent.com/79202140/158051694-21d1eab7-92d5-4a1d-8fa0-c4c07b37668d.png)

**Comment by Sitolam** [comment]
> Please check this on this beta build.
> https://t.me/pixelifysupport/16388

Thanks
