### ISSUE TITLE
Next generation assistant not working

### ISSUE THREAD

**Issue by Atarpara** [Kingsman44/Pixelify#68]
Next generation assistant not working on miui china rom. It shows error not available in your language. My Phone language is English (United States).

![Screenshot_2022-03-14-22-21-59-215_com.google.android.googlequicksearchbox.jpg](https://user-images.githubusercontent.com/66815072/158224323-15a4eb55-68cd-434a-a286-f88cce71b751.jpg)

System info

Device Name: aliothin
Miui Version: 22.2.28 china beta

**Logs**

=============
   Pixelify 2.01
   SDK version: 31
=============
---- Installation Logs Started ----

 - Network is Online

- Device info -
Codename: aliothin
Model: M2012K11AI
security patch: 2021-10-05
Magisk version: 24301
Android version: 12 (S)
 - Device info -

- Fetching version of online packages

- NGA version: 1.2
- Pixel Live Wallpapers version: 1.2
- Device Personalisation Services version: 2.0
- Pixel Launcher (31) version: 1.3

 - Removing GoogleCamera_6gb_or_more_ram.xml as device has less than 6Gb Ram
- Using chooseport method for Volume keys
- Extracting Files ...
 - Oxygen OS or MiUI or One Ui Rom Detected
 - Dropping ro.product.vendor.name, ro.product.vendor.device, ro.product.vendor.model, ro.product.vendor.brand prop from spoof.prop
 - Installing Android System Intelligence
 - Backup Detected for Android System Intelligence
 - Installing Next generation assistant
 - Making Google system app
 - Skipping Pixel Wallpapers
 - Skipping Pixel Bootanimation
 - Skipping Pixel Launcher
 - Skipping Extreme Battery Saver (Flipendo)
 - Patching Google Keyboard's bools
 - Making Google Keyboard as system app
 - Making Google TTS system app
 - Generatings permission for package: com.google.intelligence.sense
 - Generatings permission for package: com.google.android.as.oss
 - Generatings permission for package: com.google.android.as
 - Generatings permission for package: com.google.android.odad
 - Generatings permission for package: com.google.android.settings.intelligence
 - Generatings permission for package: com.google.android.googlequicksearchbox
 - Generatings permission for package: com.google.android.apps.turbo
 
- Replacing apps 

 ---- Installation Finished ----

**Comment by Atarpara** [comment]
I tried all troubleshoot on telegram but it's not working.

**Comment by Atarpara** [comment]
I think in china based miui rom needs to  assistant permission.

![Screenshot_2022-03-25-21-30-53-459_com.google.android.googlequicksearchbox.jpg](https://user-images.githubusercontent.com/66815072/160222388-c1fa023f-f711-471a-8660-ed4e8e0123ce.jpg)

**Comment by Kingsman44** [comment]
Probably, china banned it to set as default assist app so i can't do anything about it.

**Comment by Atarpara** [comment]
can be change permission for this type of roms.
