### ISSUE TITLE
[Bug Report] Pixelify makes audio broken

### ISSUE THREAD

**Issue by entr0pia** [Kingsman44/Pixelify#69]
Pixelify version: `v2.01`
Magisk version: `24.3`
Android version: `12`
Device: `Sony Xperia 5II`

---

When playing audio (e.g. poweramp), the sound is always intermittent, and then goes back to the first few seconds and repeat intermittent. I've tried multiple configurations, and even with minimal features enabled, the issue still occurs.

**Comment by Kingsman44** [comment]
Disable now playing

**Comment by entr0pia** [comment]
> Disable now playing

Thanks. The audio works fine, now.

**Comment by GreyBoyTinker** [comment]
Hi, 

Smae issue here, except I did disable 'Now playing' and I'm still facing the same issue... Any idead?
