### ISSUE TITLE
MIUI 12.5 - Screen Attention Service

### ISSUE THREAD

**Issue by pkejval** [Kingsman44/Pixelify#77]
I'm interested in Screen Attention Service (should keep screen on when you are looking at it). How to enable this function? I can't see any new option in Display options.

**Comment by pkejval** [comment]
No. I'll try install it.

**Comment by pkejval** [comment]
Yes, it was it. Installed ASI and oprion appeared in display settings. Thanks and sorry for opening issue.

**Comment by Kingsman44** [comment]
no problem
