### ISSUE TITLE
I am sharing the system generated error code

### ISSUE THREAD

**Issue by cehnemdark** [Kingsman44/Pixelify#78]
I was also able to choose only one live wallpaper
• https://paste.crdroid.net/ROeF4i
and I left a screen recording

https://user-images.githubusercontent.com/49096330/161654275-609604c7-57a4-41f7-8f4f-f59fb56a2bcc.mp4

**Comment by Kingsman44** [comment]
Hi, i am aware of it, it fixed on beta build. you can access it on telegram grp, sry for inconvenience

**Comment by Kingsman44** [comment]
This is fixed, if still facing some issues feel free to reopen this issue
