### ISSUE TITLE
Spelling mistake in installer

### ISSUE THREAD

**Issue by Netherquark** [Kingsman44/Pixelify#79]
![Screenshot_20220410-104042_Magisk~2.png](https://user-images.githubusercontent.com/65618735/162602473-e98a10ad-b7eb-4f75-92f3-aee5125dc8ea.png)

**Comment by cjs1502** [comment]
What os and version are you using?
I tried few pixelify releases but i always got an error stating no network detected.

**Comment by Netherquark** [comment]
This is with latest magisk and pixelify on Android 12 (Fork LineageOS) on my Redmi Note 9S (Curtana/Miaitoll)
