### ISSUE TITLE
Google Play Store crashes instantly 

### ISSUE THREAD

**Issue by JerryleThree** [Kingsman44/Pixelify#82]
Running Android 12 and Using Version 2.01. Cleared storage for the Play Store and it still crashes every time. When I uninstalled Pixelify it started to work again. Reinstalling essentially disabled it again though I am able to install apps on my desktop through the Google Play website

**Comment by JerryleThree** [comment]
Factory reset and reinstalled. I had the module install the pixel launcher vs Installing it myself and everything seems to work fine now.

**Comment by JerryleThree** [comment]
Had to reinstall Magisk because I lost root for some odd reason. Reinstalled Pixelify and the Pixel Launcher through it and the Play Store is now refusing to work again. YASNAC says the device passes the Safteynet Attestation, when uninstalling Pixelify the Google Play Store launches without any issues

**Comment by Kingsman44** [comment]
I am working to fix, hopefully it will be fixed on next version

**Comment by Kingsman44** [comment]
This is fixed, if still facing some issues feel free to reopen this issue
