### ISSUE TITLE
Call recording and now playing doesn't work.

### ISSUE THREAD

**Issue by the4anoni** [Kingsman44/Pixelify#84]
Hi, like in topic.
Device: Galaxy S10
ROM: PE12
![Screenshot_20220421-060318_Phone](https://user-images.githubusercontent.com/13403084/164369991-7adfd32b-441f-4065-bbbc-3624b399b92c.png)

Now playing is stuck like this, and doesn't detect songs.
![Screenshot_20220421-060302_Android System Intelligence](https://user-images.githubusercontent.com/13403084/164370094-808e03bf-2c62-40f6-ac90-0bf795d3f9e0.png)

**Comment by Kingsman44** [comment]
Okay, can you tell me your country?

for now playing it only works on pixel devices

**Comment by the4anoni** [comment]
> Okay, can you tell me your country?
> 
> for now playing it only works on pixel devices

Poland

**Comment by Kingsman44** [comment]
Now playing wont work, it only works on pixel devices. Call recording should be now fixed

**Comment by memehammad** [comment]
Where can you find the now playing settings? I want to disable it to fix laggy media but I can't find it anywhere.
