### ISSUE TITLE
Add ability to configure module with config file

### ISSUE THREAD

**Issue by pacjo** [Kingsman44/Pixelify#85]
Would it be possible to add a feature where you can configure module settings with the use of a configuration file? (something like [NanoDroid](https://gitlab.com/Nanolx/NanoDroid) or [NikGapps](https://nikgapps.com/misc/2022/02/22/NikGapps-Config.html) use) This would allow for instalation without user interaction or provide a way of installation for people having issues with volume buttons.

**Comment by Kingsman44** [comment]
It's already there, plz read description.
