### ISSUE TITLE
When I install the module, the attached application gives an error

### ISSUE THREAD

**Issue by Rahmikarayigit** [Kingsman44/Pixelify#86]
![Screenshot_20220421-213550](https://user-images.githubusercontent.com/104170966/164557157-b6e6fc71-c3fc-4aef-93ff-9f7eb4d14720.png)

https://paste.crdroid.net/hCIGJ6

**Comment by Kingsman44** [comment]
This should be fixed on new build, if still facing issue feel free to reopen this issue
