### ISSUE TITLE
Overview selection doesn't work 

### ISSUE THREAD

**Issue by AvirukBasak** [Kingsman44/Pixelify#87]
Android 12
crDroid 8.4
Magisk 24.3

Screenshots attached

- Clicking 'Select' to start overview selection (image 2)
- tapping on any highlighted text
- text not selected
- reattempt selection
- no image or text highlighted
- force stopping 'Android System Intelligence' restores to image 1.

### Image 1
![Normal](https://user-images.githubusercontent.com/79701644/166618931-b430f752-fcea-4a22-b950-e04bbbcf31df.png)

### Image 2
![Text selection](https://user-images.githubusercontent.com/79701644/166618927-b47a96ce-3707-457f-96d2-25d290a27250.png)

### Image 3
![Text selection 2](https://user-images.githubusercontent.com/79701644/166618933-b3bae5ec-e014-4f68-9cb5-1306fa973ec9.png)

**Comment by daudix-UFO** [comment]
Same, lineageos 19.1 , Pixel 3

**Comment by Kingsman44** [comment]
Plz try beta in Pixelify Telegram group

**Comment by AvirukBasak** [comment]
> Plz try beta in Pixelify Telegram group

I just installed `Pixelify-v2.02-beta-4.zip`. Issue persists.

Also wanted to mention the following bug (black search bar)

![Screenshot_20220509-114556_Pixel Launcher](https://user-images.githubusercontent.com/79701644/167351486-87537a66-9786-4c85-a329-88d9a466c1d4.png)

**Comment by Kingsman44** [comment]
You having issues in crdroid 8.4 right? 12.1? I will try shifting myself to crdroidandroid and try to fix it.

(beta 5 is already there) https://t.me/pixelifysupport/38231

**Comment by AvirukBasak** [comment]
yes, crDroid 8.4 but it's Android 12, not 12.1

**Comment by Kingsman44** [comment]
Does it now work in now build?

**Comment by AvirukBasak** [comment]
Unfortunately no, I'm using English (US)

video: https://photos.app.goo.gl/Au5VDRtHyN8Ns45H9
pixelify install logs: [logs.txt](https://github.com/Kingsman44/Pixelify/files/8698104/logs.txt)

Just noticed, data access of Android System Intelligence is turned off and grayed out.

![Screenshot_20220516-131708_Settings](https://user-images.githubusercontent.com/79701644/168544007-cd3a7180-1342-45bb-84c4-d0f6e392dd2a.png)

**Comment by Kingsman44** [comment]
This is fixed in v2.1
