### ISSUE TITLE
Boot animation not changes

### ISSUE THREAD

**Issue by daudix-UFO** [Kingsman44/Pixelify#88]
Lineageos 19.1, Magisk 24.3, Pixel 3, Zygisk Enabled, Animation not changes from lineageos one

**Comment by Kingsman44** [comment]
Some devices start bootanimation before magisk replace all files.

open terminal
su
bootanimation

If is shows google bootanimation reason is above due to i mention. If not plz let me know.

**Comment by daudix-UFO** [comment]
Yes, bootanimation shows Google animation, so possibly it LineageOS problem, only thing I know that in LineageOS 18 animation worked fine

**Comment by Kingsman44** [comment]
it's not rom problem, but problem is starting of bootanimation before data is mounted ( Your Dev might done it )
