### ISSUE TITLE
Photos Original quality unlimited uploads

### ISSUE THREAD

**Issue by rrevanth** [Kingsman44/Pixelify#9]
Hi,

The mod works really great on OOS after removing some props from spoof.prop. I was wondering if there is a way to get unlimited original quality uploads in google photos like some custom roms have right now ( Evolution X, Pixel Experience, Pixel Extended ) with this module.

**Comment by Kingsman44** [comment]
Hi,

To get Unlimited storage on some custom rom, they are spoofing to Google Pixel 1 only for the photos app via zygote. Unfortunately we can't set Pixel model only for the photos app from magisk module now.

Which Props you had removed in spoof.prop for OOS?

**Comment by rrevanth** [comment]
I had to remove the two lines below to get the brightness issue fixed in OOS.

ro.product.vendor.device=redfin
ro.product.vendor.manufacturer=Google

Even removing the entire product.vendor props didn't break anything. I was able to get all features like High quality unlimited uploads, adaptive sound, heads up, google fit features.

**Comment by rrevanth** [comment]
I found this module via telegram group that makes Google photos think that it has unlimited original while having other features in other apps.


But the uploads are still getting counted. Can that be reverse engineered?

**Comment by Kingsman44** [comment]
> I had to remove the two lines below to get the brightness issue fixed in OOS.
> 
> ro.product.vendor.device=redfin
> ro.product.vendor.manufacturer=Google
> 
> Even removing the entire product.vendor props didn't break anything. I was able to get all features like High quality unlimited uploads, adaptive sound, heads up, google fit features.

Thanks for it, i Will make sure this will be fix on next update

**Comment by Kingsman44** [comment]
> I found this module via telegram group that makes Google photos think that it has unlimited original while having other features in other apps.
> 
> But the uploads are still getting counted. Can that be reverse engineered?

It not easy to reverse engineered apks, i will try afterwards

**Comment by rrevanth** [comment]
It's a magisk module. Not an apk. But I understand , I'm not going to push my luck :)

Thanks for what you're doing :)

**Comment by Kingsman44** [comment]
ohh, can send module link or anything?


> It's a magisk module. Not an apk. But I understand , I'm not going to push my luck :)
> 
> Thanks for what you're doing :)

**Comment by rrevanth** [comment]
Sure. Here is the link 

https://drive.google.com/file/d/11HtOL278yC9N3TtP57I9g1rZPnm76H8x/view?usp=drivesdk

**Comment by Kingsman44** [comment]
You will get Unlimited Storage on next update.

**Comment by rrevanth** [comment]
Just want to mention. I got to test 1.6 version.

It seems that although it shows up at pixel and shows unlimited original in photos, it's not really working and counting towards storage in OOS at least.
