### ISSUE TITLE
Translate from Recents Switcher not working

### ISSUE THREAD

**Issue by daudix-UFO** [Kingsman44/Pixelify#91]
On original Google Pixel ROM, it was working, on Pixelify it dosen't, Pixel 3, LlineageOS 19.1
**Pixel 3 - Pixelify - LineageOS 19.1**
![Report_P3](https://user-images.githubusercontent.com/77155297/168398519-ba54c378-9669-41c4-a61c-b996a5ecf0df.png)

**Pixel 3 XL - Google Stock ROM Android 12.0**
![Report_P3XL](https://user-images.githubusercontent.com/77155297/168398545-77ff99ca-90ef-4c43-b19e-c933d2b04401.png)

**Comment by Kingsman44** [comment]
Well, you have translate app, if you want i can force enable translate button

**Comment by daudix-UFO** [comment]
@Kingsman44 let's try!

**Comment by Kingsman44** [comment]
This is fixed in v2.1
