### ISSUE TITLE
Google Photos unlimited backup not working

### ISSUE THREAD

**Issue by fuwwy** [Kingsman44/Pixelify#95]
All google apps including Google Play Services and Google Photos are enabled on DenyList, backup still takes up storage space.

**Comment by fuwwy** [comment]
It seems like there's an issue with how Universal SafetyNet Fix needs to remove Google Play Services from denylist in order to work

**Comment by Kingsman44** [comment]
I will check it today.

**Comment by Kingsman44** [comment]
Which rom? and can share pixelify installation logs?
