### ISSUE TITLE
Adaptive connectivity stopping 

### ISSUE THREAD

**Issue by RizwanXt** [Kingsman44/Pixelify#98]
After installing on pixel 4xl adaptive connectivity keeps stopping

I only need unlimited storage how can I get I need standalone module for photos only

**Comment by Kingsman44** [comment]
Can share logs of crash?

**Comment by RizwanXt** [comment]
> Can share logs of crash?

How to share???

**Comment by Kingsman44** [comment]
Use matlog from playstore.
also Does it crash all the time or on the starting?

**Comment by RizwanXt** [comment]
It only showing after restarting device and another thing I can't install system updates

**Comment by Kingsman44** [comment]
This is fixed in v2.1
